# Pull-based OTA firmware updates from GitHub Pages
# Include this package to enable automatic firmware updates.
# Requires device_name and friendly_name substitutions.
# The update entity appears in Home Assistant with built-in
# check and install controls.

http_request:

ota:
  - platform: http_request

update:
  - platform: http_request
    id: firmware_update
    name: "${friendly_name} Firmware Update"
    source: https://rluengen.github.io/esphome/firmware/${device_name}/manifest.json
    update_interval: never

esphome:
  on_boot:
    priority: -10
    then:
      - delay: 10s
      - update.check: firmware_update

button:
  - platform: template
    name: "Check for Update"
    icon: mdi:update
    entity_category: config
    on_press:
      - update.check: firmware_update
