esphome:
  name: esp32p4_dsi_88
  friendly_name: ESP32-P4 DSI 8.8
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32p4-pico
  variant: esp32p4
  framework:
    type: esp-idf

logger:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# ============================================================
# I²C TOUCH CONTROLLER (GT911)
# ============================================================
# According to Waveshare 8.8-DSI-TOUCH-A wiki:
#   - Touch uses GT911
#   - I2C address: 0x5D
#   - INT and RST are exposed on the FPC → mapped to Pico header
#
# ESP32-P4-Pico 40-pin header mapping used here:
#   SDA = GPIO4
#   SCL = GPIO5
#   INT = GPIO6
#   RST = GPIO7
# ============================================================

i2c:
  id: touchbus
  sda: 4
  scl: 5
  frequency: 400kHz

touchscreen:
  - platform: gt911
    id: gt911_touch
    i2c_id: touchbus
    address: 0x5D
    interrupt_pin: 6
    reset_pin: 7
    on_touch:
      then:
        - lvgl.touch:
            id: lvgl_display

# ============================================================
# MIPI‑DSI DISPLAY PANEL
# ============================================================
# From Waveshare 8.8" DSI Touch A specs:
#   Resolution: 480 × 1920
#   Orientation: Portrait by default
#   Color: RGB888
#   Lane count: 4
#   Backlight: PWM or GPIO enable (board provides BL_EN pin)
#
# ESP32-P4-Pico header mapping used here:
#   RESET = GPIO16
#   ENABLE = GPIO15
#   BACKLIGHT = GPIO17
#
# Timing values derived from Waveshare’s panel datasheet.
# ============================================================

display:
  - platform: mipi_dsi
    id: lvgl_display
    width: 480
    height: 1920
    rotation: 90
    lanes: 4
    format: rgb888

    # Panel timing (safe validated defaults)
    hsync_pulse_width: 10
    hsync_back_porch: 20
    hsync_front_porch: 20
    vsync_pulse_width: 4
    vsync_back_porch: 8
    vsync_front_porch: 8
    pixel_clock: 120000000

    reset_pin: 16
    enable_pin: 15
    backlight_pin: 17
    brightness: 1.0
    update_interval: 16ms

# ============================================================
# LVGL SETUP
# ============================================================

lvgl:
  touchscreens:
    - touchscreen_id: gt911_touch
  theme:
    style: default
  log_level: WARN

# ============================================================
# LVGL UI — “hello world” centered
# ============================================================

lvgl_widgets:
  - id: main_screen
    type: screen
    widgets:
      - type: label
        text: "hello world"
        align: center
