# ============================================================
# ESP32-P4-Pico with 8.8" DSI Touch Display
# Based on Waveshare ESP32-P4-ETH 10.1" example
# Modified for 8.8" DSI screen without internet
# ============================================================

substitutions:
  device_name: controller
  friendly_name: Display Controller
  project_name: Display Controller
  project_version: "1.0.0"
  log_level: VERBOSE

esphome:
  name: esp32p4-dsi-88
  friendly_name: ESP32-P4 DSI 8.8
  on_boot:
    priority: -100
    then:
      - lambda: |-
          // Set backlight to maximum brightness
          id(display_backlight_i2c).write_byte(0xab, 0x00);  // 0x00 = max brightness
          id(display_backlight_i2c).write_byte(0xaa, 0x01);  // Apply setting

esp32:
  board: esp32-p4-evboard
  variant: esp32p4
  flash_size: 16MB
  framework:
    type: esp-idf

esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml

# Required for MIPI-DSI display
psram:
  mode: hex
  speed: 200MHZ

esp_ldo:

logger:
  level: DEBUG
  hardware_uart: UART0

# ============================================================
# I2C for GT911 Touchscreen
# ============================================================
# ESP32-P4-Pico pinout:
#   SDA = GPIO7
#   SCL = GPIO8
# ============================================================

i2c:
  sda: GPIO7
  scl: GPIO8
  frequency: 400kHz
  scan: true

# I2C device for backlight control (address 0x45)
i2c_device:
  - address: 0x45
    id: display_backlight_i2c

# ============================================================
# Backlight Control
# ============================================================
# Waveshare DSI displays use I2C for backlight:
#   Register 0xab = brightness (0x00=max, 0xff=off, inverted)
#   Register 0xaa = enable (write 0x01 to apply)
# ============================================================

# Backlight brightness control as a light
output:
  - platform: template
    id: backlight_output
    type: float
    write_action:
      - lambda: |-
          uint8_t brightness = 255 - (uint8_t)(state * 255);
          id(display_backlight_i2c).write_byte(0xab, brightness);
          id(display_backlight_i2c).write_byte(0xaa, 0x01);

light:
  - platform: monochromatic
    name: "Display Backlight"
    id: display_backlight
    output: backlight_output
    default_transition_length: 250ms
    restore_mode: ALWAYS_ON

# ============================================================
# MIPI-DSI Display - 8.8" Touch (480x1920)
# ============================================================
# Waveshare 8.8" DSI Touch A specs:
#   Display IC: OTA7290B
#   Touch IC: GT9271 (GT911 compatible)
#   Resolution: 480 x 1920 (portrait)
#   Interface: MIPI-DSI
#
# Timing parameters from Raspberry Pi kernel driver:
#   https://github.com/raspberrypi/linux/blob/rpi-6.6.y/drivers/gpu/drm/panel/panel-waveshare-dsi.c
# ============================================================

display:
  - platform: mipi_dsi
    id: dsi_display
    model: CUSTOM
    rotation: 90
    dimensions:
      width: 480
      height: 1920
    lanes: 2
    color_order: rgb
    # Timing from official Raspberry Pi kernel driver (ws_panel_8_8_mode)
    # clock = 83333 kHz = ~83.3 MHz
    hsync_front_porch: 50
    hsync_pulse_width: 50
    hsync_back_porch: 50
    vsync_front_porch: 20
    vsync_pulse_width: 20
    vsync_back_porch: 20
    pclk_frequency: 83MHz
    lane_bit_rate: 1Gbps
    # OTA7290B initialization sequence
    init_sequence:
      # Exit sleep mode
      - [0x11]
      - delay 120ms
      # Set display on
      - [0x29]
      - delay 20ms

# ============================================================
# GT911 Touchscreen
# ============================================================

touchscreen:
  - platform: gt911
    id: dsi_touchscreen
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: false
    on_touch:
      - logger.log:
          format: "Touch at (%d, %d)"
          args: [touch.x, touch.y]

# ============================================================
# LVGL Graphics
# ============================================================

lvgl:
  displays:
    - dsi_display
  touchscreens:
    - dsi_touchscreen
  color_depth: 16
  buffer_size: 100%
  byte_order: little_endian
  on_idle:
    - timeout: 30s
      then:
        - logger.log: "Display idle timeout"
  pages:
    - id: main_page
      skip: false
      bg_color: 0x000000
      bg_opa: cover
      widgets:
        - label:
            text: "Hello World"
            align: CENTER
            text_color: 0xFFFFFF
