# https://github.com/patrickcollins12/esphome-fan-controller

# enable ntc sensor gpio

# AHT20 Pin	ESP32 Pin
# VCC	3.3V
# GND	GND
# SDA	GPIO21
# SCL	GPIO22

substitutions:
  device_name: dehumidifier
  friendly_name: Dehumidifier
  project_name: Van Dehumidifier
  project_version: "1.0.0"
  log_level: VERBOSE

# added for debugging
web_server:
  port: 80

esphome:
  name: dehumidifier
  friendly_name: ${friendly_name}
  project:
    name: smartvan.${project_name}
    version: ${project_version}
  on_boot:
    priority: 600
    then:
      - lambda: |-
          int reason = esp_reset_reason();
          const char* reason_str;
          switch(reason) {
            case 1: reason_str = "POWERON (normal boot)"; break;
            case 2: reason_str = "EXTERNAL RESET"; break;
            case 3: reason_str = "SOFTWARE RESET"; break;
            case 4: reason_str = "PANIC/EXCEPTION - CRASH!"; break;
            case 5: reason_str = "INTERRUPT WATCHDOG - CRASH!"; break;
            case 6: reason_str = "TASK WATCHDOG - CRASH!"; break;
            case 7: reason_str = "WATCHDOG - CRASH!"; break;
            case 8: reason_str = "DEEPSLEEP RESET"; break;
            case 9: reason_str = "BROWNOUT - POWER ISSUE!"; break;
            case 10: reason_str = "SDIO RESET"; break;
            default: reason_str = "UNKNOWN"; break;
          }
          ESP_LOGW("boot", "ESP32 boot reason: %s (code %d)", reason_str, reason);

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
      - path: devices/ESP32-Relay-x2.yaml
        vars:
          relay_1_id: compressor_relay_switch
          relay_2_id: fan_relay_switch

api:
  services:
    - service: set_humidity_target
      variables:
        target: float
      then:
        - number.set:
            id: humidity_target
            value: !lambda 'return target;'

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

# https://esphome.io/components/sensor/ntc/
sensor:
# GPIO25 ──┬── 5.6kΩ Resistor ──┬── NTC Thermistor ── GND
#          │                    │
#          │                  ADC Pin (GPIO33)
#          │
#       (GPIO25 VCC control to prevent self-heating)
  - platform: ntc
    sensor: resistance_sensor
    calibration:
      # 3-point Steinhart-Hart calibration
      - 23320.2Ohm -> 0°C      # Ice water
      - 13791.4Ohm -> 21.7°C   # Room temp
      - 7136.0Ohm -> 32.8°C    # Warm water (91°F)
    name: "Defrost Temperature"
    id: defrost_temp_c
    unit_of_measurement: "°C"

  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 5.6kOhm
    name: Resistance Sensor

  # https://esphome.io/components/sensor/ntc/#self-heating
  # Manual updates only - controlled by interval to prevent self-heating
  - platform: adc
    id: source_sensor
    pin: GPIO33
    attenuation: 12db  # For full 0-3.3V range
    update_interval: never

  - platform: aht10
    variant: AHT20
    temperature:
      name: "Ambient Temperature"
      id: ambient_temp
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    humidity:
      name: "Ambient Humidity"
      id: ambient_humidity
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    update_interval: 10s

interval:
  # NTC reading interval with self-heating prevention
  - interval: 10s
    then:
      - switch.turn_on: ntc_vcc
      - delay: 100ms  # Allow voltage to stabilize
      - component.update: source_sensor
      - delay: 50ms   # Allow reading to complete
      - switch.turn_off: ntc_vcc

  - interval: 30s
    then:
      - logger.log:
          format: "[Dehumidifier] Interval check - Humidity: %.1f%%, Target: %.1f%%, Power: %s, Defrost: %s"
          args: 
            - 'id(ambient_humidity).state'
            - 'id(humidity_target).state'
            - 'id(dehumidifier_power).state ? "ON" : "OFF"'
            - 'id(defrost_mode).state ? "ON" : "OFF"'
      - if:
          condition:
            lambda: 'return isnan(id(ambient_humidity).state);'
          then:
            - logger.log: "[Dehumidifier] Humidity sensor reading NaN - turning off for safety"
            - switch.turn_off: compressor_relay_switch
            - switch.turn_off: fan_relay_switch
          else:
            - logger.log: "[Dehumidifier] Valid humidity reading - proceeding with control logic"
            - if:
                condition:
                  and:
                    - switch.is_on: dehumidifier_power  # Only when enabled
                    - binary_sensor.is_off: defrost_mode  # Not in defrost
                then:
                  - logger.log: "[Dehumidifier] Checking humidity against target values"
                  - if:
                      condition:
                        lambda: 'return id(ambient_humidity).state > (id(humidity_target).state + 2.0);'
                      then:
                        - if:
                            condition:
                              switch.is_off: compressor_relay_switch
                            then:
                              - logger.log:
                                  format: "[Dehumidifier] Starting - humidity %.0f%% > target %.1f%%"
                                  args: ['id(ambient_humidity).state', 'id(humidity_target).state']
                              - delay: 500ms  # Small delay before switching relay
                              - logger.log: "[Dehumidifier] Turning on fan relay"
                              - switch.turn_on: fan_relay_switch
                              - delay: 5s  # Longer delay - let fan spin up and power stabilize
                              - logger.log: "[Dehumidifier] Turning on compressor relay"
                              - switch.turn_on: compressor_relay_switch
                      else:
                        - if:
                            condition:
                              lambda: 'return id(ambient_humidity).state < (id(humidity_target).state - 2.0);'
                            then:
                              - if:
                                  condition:
                                    switch.is_on: compressor_relay_switch
                                  then:
                                    - logger.log:
                                        format: "[Dehumidifier] Stopping - humidity %.1f%% below target %.1f%% - 2%%"
                                        args: ['id(ambient_humidity).state', 'id(humidity_target).state']
                                    - logger.log: "[Dehumidifier] Turning off compressor relay"
                                    - switch.turn_off: compressor_relay_switch
                                    - logger.log: "[Dehumidifier] Running fan for 30s cooldown"
                                    - delay: 30s  # Let fan run for 30s after compressor stops
                                    - logger.log: "[Dehumidifier] Turning off fan relay"
                                    - switch.turn_off: fan_relay_switch
                            else:
                              - logger.log: "[Dehumidifier] Humidity within target range - no action needed"
                else:
                  - if:
                      condition:
                        switch.is_off: dehumidifier_power
                      then:
                        - logger.log: "[Dehumidifier] Disabled - ensuring relays are off"
                        - switch.turn_off: compressor_relay_switch
                        - switch.turn_off: fan_relay_switch
                      else:
                        # Dehumidifier is on but in defrost mode
                        - logger.log: "[Dehumidifier] Defrost mode - compressor off, fan running"
                        - switch.turn_off: compressor_relay_switch
                        - delay: 500ms  # Delay before switching fan relay
                        - switch.turn_on: fan_relay_switch

number:
  - platform: template
    name: "Humidity Target"
    id: humidity_target
    min_value: 30
    max_value: 70
    step: 1
    unit_of_measurement: "%"
    initial_value: 60
    optimistic: true
    restore_value: true
    entity_category: config
    mode: box

  - platform: template
    name: "Defrost Exit Temperature"
    id: defrost_exit_temp
    min_value: 3
    max_value: 10
    step: 0.5
    unit_of_measurement: "°C"
    initial_value: 5.0
    optimistic: true
    entity_category: config
    mode: box

# automatically go into defrost mode if the temperature is < 2C
binary_sensor:
  - platform: template
    name: "Defrost Mode"
    id: defrost_mode
    lambda: |-
      //return id(defrost_temp_c).state < 2.0;
      return false;
    on_press:
      - logger.log:
          format: "[Defrost] Mode STARTED - coil temperature below threshold"
          args: []
#       - switch.turn_off: compressor_relay_switch  # Turn off compressor during defrost
#       - switch.turn_on: fan_relay_switch  # Keep fan running to circulate air
#       - logger.log: 
#           format: "Waiting for defrost temperature to reach %.1f°C"
#           args: ['id(defrost_exit_temp).state']
#       # Wait until temperature rises above the defrost exit threshold
#       - wait_until:
#           condition:
#             lambda: 'return id(defrost_temp_c).state > id(defrost_exit_temp).state;'
#           timeout: 30min  # Safety timeout in case sensor fails
#       - if:
#           condition:
#             lambda: 'return id(defrost_temp_c).state > id(defrost_exit_temp).state;'
#           then:
#             - logger.log: "Defrost cycle complete - temperature threshold reached"
#           else:
#             - logger.log: "Defrost cycle timed out after 30 minutes"
    on_release:
      - logger.log:
          format: "[Defrost] Mode ENDED - temperature recovered above %.1f°C"
          args: ['id(defrost_exit_temp).state']

  - platform: template
    name: "Compressor"
    id: compressor_active
    lambda: 'return id(compressor_relay_switch).state;'
    device_class: power
    entity_category: diagnostic   # Optional grouping

  - platform: template
    name: "Fan"
    id: fan_active
    lambda: 'return id(fan_relay_switch).state;'
    device_class: power
    entity_category: diagnostic

switch:
  - id: !extend compressor_relay_switch
    name: "Compressor Relay"
    # internal: true

  - id: !extend fan_relay_switch
    name: "Fan Relay"
    # internal: true

  - platform: gpio
    pin: GPIO25
    id: ntc_vcc
    name: "NTC Thermistor VCC Control"
    restore_mode: ALWAYS_OFF  # Keep off to prevent self-heating
    internal: true

  - platform: template
    name: "Dehumidifier"
    id: dehumidifier_power
    icon: "mdi:air-humidifier"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

