# https://github.com/patrickcollins12/esphome-fan-controller
# fan isn't PWM controlled.
# Dehumidifier control

substitutions:
  device_name: dehumidifier
  friendly_name: Dehumidifier
  
project_version: "1.0.0"

packages:
  - !include templates/common.yaml
  - !include templates/network/wifi.yaml
  - !include templates/time/homeassistant.yaml

api:
  services:
    - service: set_humidity_target
      variables:
        target: float
      then:
        - number.set:
            id: humidity_target
            value: !lambda 'return target;'

# https://esphome.io/components/sensor/ntc/
sensor:
  - platform: ntc
    sensor: adc1
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
      nominal_resistance: 10kOhm
    name: "Defrost Temperature"
    id: defrost_temp_c
    unit_of_measurement: "°C"
    update_interval: never

  - platform: dht
    pin: GPIO21
    temperature:
      name: "Ambient Temperature"
      id: ambient_temp
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    humidity:
      name: "Ambient Humidity"
      id: ambient_humidity
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    model: DHT22
    update_interval: 10s

number:
  - platform: template
    name: "Humidity Target"
    id: humidity_target
    min_value: 30
    max_value: 70
    step: 1
    unit_of_measurement: "%"
    initial_value: 60
    optimistic: true

#output:
#  - platform: ledc
#    pin: GPIO18
#   frequency: 25000 Hz
#    id: fan_pwm
#
#fan:
#  - platform: speed
#    output: fan_pwm
#    name: "Dehumidifier Fan"
#    id: dehumidifier_fan
#    speed_count: 3



# automatically go into defrost mode if the temperature is < 2C
binary_sensor:
  - platform: template
    name: "Defrost Mode"
    id: defrost_mode
    lambda: |-
      return id(defrost_temp_c).state < 2.0;

  - platform: template
    name: "Compressor"
    id: compressor_active
    lambda: 'return id(compressor_relay_switch).state;'
    device_class: power
    entity_category: diagnostic   # Optional grouping

  - platform: template
    name: "Fan"
    id: fan_active
    lambda: 'return id(fan_relay_switch).state;'
    device_class: power
    entity_category: diagnostic

switch:
  - platform: gpio
    pin: GPIO22
    name: "Compressor Relay"
    id: compressor_relay_switch
    internal: true

  - platform: gpio
    pin: GPIO23
    name: "Fan Relay"
    id: fan_relay_switch
    internal: true

  - platform: gpio
    pin: D0
    id: ntc_vcc
    internal: true

  - platform: template
    name: "Dehumidifier"
    id: dehumidifier_power
    icon: "mdi:air-humidifier"
    lambda: |-
      // Report ON if either relay is energized.
      return id(compressor_relay_switch).state || id(fan_relay_switch).state;
    on_turn_on:
      - if:
          condition:
            binary_sensor.is_off: defrost_mode
            lambda: 'return id(ambient_humidity).state > id(humidity_target).state;'
          then:
            - switch.turn_on: fan_relay_switch
            - switch.turn_on: compressor_relay_switch
          else:
            - logger.log: "Dehumidifier blocked (defrost mode active)"
    on_turn_off:
      - switch.turn_off: compressor_relay_switch
      - switch.turn_off: fan_relay_switch
    restore_mode: RESTORE_DEFAULT_OFF

# https://esphome.io/components/sensor/ntc/#self-heating
interval:
  - interval: 60s
    then:
      - switch.turn_on: ntc_vcc
      - component.update: source_sensor
      - switch.turn_off: ntc_vcc

automation:
  - alias: "Dehumidifier Control"
    trigger:
      - platform: time
        seconds: /10
    condition:
      - condition: not
        binary_sensor.is_on: defrost_mode
      - switch.is_on: dehumidifier_power 
    action:
      - if:
          condition:
            lambda: 'return id(ambient_humidity).state > id(humidity_target).state;'
          then:
            - switch.turn_on: compressor_relay_switch
            - switch.turn_on: fan_relay_switch
          else:
            - switch.turn_off: compressor_relay_switch
            - switch.turn_off: fan_relay_switch
