# https://github.com/patrickcollins12/esphome-fan-controller
# fan isn't PWM controlled.
# Dehumidifier control

substitutions:
  device_name: dehumidifier
  friendly_name: Dehumidifier
  project_name: Van Dehumidifier
  project_version: "1.0.0"

esphome:
  name: dehumidifier
  friendly_name: ${friendly_name}
  project:
    name: smartvan.${project_name}
    version: ${project_version}

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
      - path: devices/kincony-kc868-a2v3-sp32-s3.yaml
        vars:
          relay_1_id: compressor_relay_switch
          relay_2_id: fan_relay_switch

api:
  services:
    - service: set_humidity_target
      variables:
        target: float
      then:
        - number.set:
            id: humidity_target
            value: !lambda 'return target;'

# https://esphome.io/components/sensor/ntc/
sensor:
  - platform: ntc
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25째C
      reference_resistance: 10kOhm
    name: "Defrost Temperature"
    id: defrost_temp_c
    unit_of_measurement: "째C"

  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 5.6kOhm
    name: Resistance Sensor

  - platform: adc
    id: source_sensor
    pin: GPIO1

    # https://esphome.io/components/sensor/ntc/#self-heating


  - platform: dht
    pin: GPIO2
    temperature:
      name: "Ambient Temperature"
      id: ambient_temp
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1

    humidity:
      name: "Ambient Humidity"
      id: ambient_humidity
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    model: DHT22
    update_interval: 10s

interval:
  # Update the NTC sensor every 60 seconds to prevent the self-heating effect
  - interval: 60s
    then:
      - switch.turn_on: ntc_vcc
      - component.update: source_sensor
      - switch.turn_off: ntc_vcc
  
  - interval: 30s  # Check humidity every 30 seconds
    then:
      - if:
          condition:
            and:
              - switch.is_on: dehumidifier_power  # Only when enabled
              - binary_sensor.is_off: defrost_mode  # Not in defrost
          then:
            - if:
                condition:
                  lambda: 'return id(ambient_humidity).state > (id(humidity_target).state + 2.0);'
                then:
                  - if:
                      condition:
                        switch.is_off: compressor_relay_switch
                      then:
                        - logger.log: "Starting dehumidifier - humidity too high"
                        - switch.turn_on: fan_relay_switch
                        - delay: 2s  # Start fan first
                        - switch.turn_on: compressor_relay_switch
                else:
                  - if:
                      condition:
                        lambda: 'return id(ambient_humidity).state < (id(humidity_target).state - 2.0);'
                      then:
                        - if:
                            condition:
                              switch.is_on: compressor_relay_switch
                            then:
                              - logger.log: "Stopping dehumidifier - target humidity reached"
                              - switch.turn_off: compressor_relay_switch
                              - delay: 30s  # Let fan run for 30s after compressor stops
                              - switch.turn_off: fan_relay_switch
          else:
            - if:
                condition:
                  or:
                    - switch.is_off: dehumidifier_power
                    - binary_sensor.is_on: defrost_mode
                then:
                  - switch.turn_off: compressor_relay_switch
                  - switch.turn_off: fan_relay_switch

number:
  - platform: template
    name: "Humidity Target"
    id: humidity_target
    min_value: 30
    max_value: 70
    step: 1
    unit_of_measurement: "%"
    initial_value: 60
    optimistic: true

  - platform: template
    name: "Defrost Exit Temperature"
    id: defrost_exit_temp
    min_value: 3
    max_value: 10
    step: 0.5
    unit_of_measurement: "째C"
    initial_value: 5.0
    optimistic: true

# automatically go into defrost mode if the temperature is < 2C
binary_sensor:
  - platform: template
    name: "Defrost Mode"
    id: defrost_mode
    lambda: |-
      return id(defrost_temp_c).state < 2.0;
    on_press:
      - script.execute: defrost_cycle
    on_release:
      - logger.log: "Defrost mode ended"

  - platform: template
    name: "Compressor"
    id: compressor_active
    lambda: 'return id(compressor_relay_switch).state;'
    device_class: power
    entity_category: diagnostic   # Optional grouping

  - platform: template
    name: "Fan"
    id: fan_active
    lambda: 'return id(fan_relay_switch).state;'
    device_class: power
    entity_category: diagnostic

switch:
  - id: !extend compressor_relay_switch
    name: "Compressor Relay"
    internal: true

  - id: !extend fan_relay_switch
    name: "Fan Relay"
    internal: true

  - platform: gpio
    pin: GPIO21
    id: ntc_vcc
    internal: true

  - platform: template
    name: "Dehumidifier"
    id: dehumidifier_power
    icon: "mdi:air-humidifier"
    optimistic: true
    lambda: |-
      // Report ON if either relay is energized.
      return id(compressor_relay_switch).state || id(fan_relay_switch).state;
    turn_on_action:
      - if:
          condition:
            and:
              - binary_sensor.is_off: defrost_mode
              - lambda: 'return id(ambient_humidity).state > id(humidity_target).state;'
          then:
            - switch.turn_on: fan_relay_switch
            - switch.turn_on: compressor_relay_switch
          else:
            - logger.log: "Dehumidifier blocked (defrost mode active or target humidity reached)"
    turn_off_action:
      - switch.turn_off: compressor_relay_switch
      - switch.turn_off: fan_relay_switch
    restore_mode: RESTORE_DEFAULT_OFF

script:
  # Safety script to prevent compressor short cycling
  - id: compressor_delay
    mode: single
    then:
      - delay: 90s  # Minimum delay between compressor cycles
      
  # Script to handle defrost cycle
  - id: defrost_cycle
    mode: restart
    then:
      - logger.log: "Starting defrost cycle"
      - switch.turn_off: compressor_relay_switch  # Turn off compressor during defrost
      - switch.turn_on: fan_relay_switch  # Keep fan running to circulate air
      - logger.log: 
          format: "Waiting for defrost temperature to reach %.1f째C"
          args: ['id(defrost_exit_temp).state']
      # Wait until temperature rises above the defrost exit threshold
      - wait_until:
          condition:
            lambda: 'return id(defrost_temp_c).state > id(defrost_exit_temp).state;'
          timeout: 30min  # Safety timeout in case sensor fails
      - if:
          condition:
            lambda: 'return id(defrost_temp_c).state > id(defrost_exit_temp).state;'
          then:
            - logger.log: "Defrost cycle complete - temperature threshold reached"
          else:
            - logger.log: "Defrost cycle timed out after 30 minutes"

# # https://github.com/esphome/esphome-docs/pull/2110/files#diff-3c675dcb29f3fd96aad388c1be4d93423f29af77d446fa1c152fd2c066addab7
# humidifier:
#       - platform: hygrostat
#         name: "Hygrostat Humidifier Controller"
#         sensor: my_humidity_sensor
#         default_target_thumidity_high: 70%
#         min_dehumidifying_off_time: 300s
#         min_dehumidifying_run_time: 300s
#         min_idle_time: 30s
#         dehumidify_action:
#           - switch.turn_on: central_fan
#         idle_action:
#           - switch.turn_off: central_fan

