# https://jnan.co/tools/esphomelvglsim/

# Dashboard to display home assistant status and weather information.

# https://wikitwist.com/how-to-use-the-seeedstudio-reterminal-e1001-with-home-assistant-via-esphome/
# https://wiki.seeedstudio.com/reterminal_e10xx_with_esphome/
# https://wiki.seeedstudio.com/reterminal_e10xx_with_esphome_advanced/

substitutions:
  device_name: terminal
  friendly_name: "Terminal Display"
  project_version: "1.0.0"
  log_level: VERBOSE
  sleep_duration: 10min

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
      - path: packages/icons/network_icons.yaml
      - path: packages/icons/battery_icons.yaml
      - path: packages/icons/weather_icons.yaml
      - path: packages/icons/homeassistant_icons.yaml
      - path: devices/reterminal-e1001.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "Terminal Dashboard Display"
  on_boot:
    priority: 600
    then:
      - logger.log: "esphome on_boot"
      - lvgl.pause:
      - output.turn_on: bsp_battery_enable
      - delay: 150ms
      - component.update: battery_voltage
      - component.update: battery_level
      - delay: 50ms
      - logger.log: "Battery sensors updated, resuming LVGL"
      - lvgl.resume:
      - component.update: epaper_display
      - output.turn_off: bsp_battery_enable
      - lambda: |-
          ESP_LOGI("esphome", "ESPHome on_boot triggered");

binary_sensor:
  - id: !extend button_left
    on_press:
      then:
        - lvgl.page.previous:
            time: 0ms

  - id: !extend button_right
    on_press:
      then:
        - lvgl.page.next:
            time: 0ms

  - id: !remove button_green

  # Battery charging status (check if USB/external power is connected)
  - platform: template
    id: battery_charging
    name: "Battery Charging"
    lambda: |-
      // Returns true if battery voltage is rising or above charging threshold
      // Adjust logic based on your hardware's charging detection
      return id(battery_voltage).state > 4.1;  // Typical charging voltage

font:
  - file: "fonts/segoeui.ttf"
    id: segoeui_16
    size: 16
    bpp: 4
  
  - file: "fonts/segoeui.ttf"
    id: segoeui_20
    size: 20
    bpp: 4
  
  - file: "fonts/segoeui.ttf"
    id: segoeui_24
    size: 24
    bpp: 4

interval:
  - interval: 10min
    then:
      - logger.log: "Update display interval"
      - component.update: epaper_display

lvgl:
  border_width: 0
  outline_width: 0
  shadow_width: 0
  text_font: segoeui_16
  align: center

  on_idle:
    timeout: 10s
    then:
      - logger.log: "LVGL on_idle"
      - lambda: |-
          ESP_LOGI("display", "on_idle");
  
  on_ready:
    then:
      - logger.log: "LVGL on_ready"
      - lambda: |-
          ESP_LOGI("display", "on_ready");

  on_pause:
    - logger.log: "LVGL on_pause"
    - lambda: |-
        ESP_LOGI("display", "on_pause");
    - if:
        condition:
          binary_sensor.is_off: battery_charging
        then:
          - logger.log: "Not charging, entering deep sleep"
          - deep_sleep.enter:
              id: deep_sleep_id
              sleep_duration: ${sleep_duration}
        else:
          - logger.log: "Charging, skipping deep sleep"

  on_resume:
    - logger.log: "LVGL on_resume"
  on_boot:
    - logger.log: "LVGL on_boot"

  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
        # Status Bar - at top of main page
        - obj:
            id: status_bar
            width: 100%
            height: 30
            align: TOP_MID
            x: 0
            y: 0
            border_width: 0
            radius: 0
            pad_all: 3
            widgets:
              # Left side: Location (lat/long)
              - label:
                  id: lbl_status_location
                  align: LEFT_MID
                  x: 5
                  text_font: segoeui_16
                  text_color: 0xFFFFFF
                  text: !lambda |-
                    if (!isnan(id(location_latitude).state) && !isnan(id(location_longitude).state)) {
                      static char buf[32];
                      snprintf(buf, sizeof(buf), "%.4f, %.4f", 
                        id(location_latitude).state, 
                        id(location_longitude).state);
                      return buf;
                    }
                    return "-- , --";

              # Center: Date
              - label:
                  id: lbl_status_date
                  align: CENTER
                  text_font: segoeui_16
                  text_color: 0xFFFFFF
                  text: !lambda |-
                    auto time = id(time_entity).now();
                    if (time.is_valid()) {
                      static char buf[40];
                      snprintf(buf, sizeof(buf), "%s %s %d, %d", 
                        time.strftime("%A").c_str(),
                        time.strftime("%B").c_str(),
                        time.day_of_month,
                        time.year);
                      return buf;
                    }
                    return "-- --, ----";

              # Right side container with flex layout
              - obj:
                  id: status_icons_container
                  align: RIGHT_MID
                  width: SIZE_CONTENT
                  height: 100%
                  bg_opa: TRANSP
                  border_width: 0
                  pad_all: 0
                  layout:
                    type: FLEX
                    flex_flow: ROW_REVERSE
                    flex_align_main: START
                    flex_align_cross: CENTER
                    pad_column: 5
                  widgets:
                    # Home Assistant status (rightmost)
                    - label:
                        id: lbl_ha_status
                        text_font: homeassistant_icons
                        text_color: 0xFFFFFF
                        text: "\U000F07D0"

                    # WiFi status
                    - label:
                        id: lbl_wifi_status
                        text_font: wifi_icons
                        text_color: 0xFFFFFF
                        text: "\U000F0928"

                    # Battery icon
                    - label:
                        id: lbl_battery_status
                        text_font: battery_icons
                        text_color: 0xFFFFFF
                        text: !lambda |-
                          if (isnan(id(battery_level).state)) return "\U000F0091";  // unknown icon
                          int x = (int)id(battery_level).state;
                          if (x >= 95) return "\U000F0079";
                          else if (x >= 85) return "\U000F0082";
                          else if (x >= 75) return "\U000F0081";
                          else if (x >= 65) return "\U000F0080";
                          else if (x >= 55) return "\U000F007F";
                          else if (x >= 45) return "\U000F007E";
                          else if (x >= 35) return "\U000F007D";
                          else if (x >= 25) return "\U000F007C";
                          else if (x >= 15) return "\U000F007B";
                          else if (x >= 5)  return "\U000F007A";
                          else return "\U000F008E";

                    # Battery percentage text (leftmost)
                    - label:
                        id: lbl_battery_percent
                        text_font: segoeui_16
                        text_color: 0xFFFFFF
                        text: !lambda |-
                          if (isnan(id(battery_level).state)) return "--%";
                          static char buf[8];
                          snprintf(buf, sizeof(buf), "%d%%", (int)id(battery_level).state);
                          return buf;

        # Weather Section (below status bar)
        - obj:
            id: weather_container
            width: 320
            height: 200
            align: TOP_MID
            x: 0
            y: 35
            bg_color: 0xFFFFFF
            border_width: 3
            border_color: 0x000000
            pad_all: 10
            widgets:
              - label:
                  id: lbl_weather_icon
                  align: TOP_MID
                  x: 0
                  y: 10
                  text_font: weather_icons
                  text_color: 0x000000
                  text: "\U000F0599"  # Default sunny icon
              
              - label:
                  id: lbl_weather_temp
                  align: TOP_MID
                  x: 0
                  y: 120
                  text_font: segoeui_24
                  text_color: 0x000000
                  text: !lambda |-
                    if (!id(weather_temp).state.empty()) {
                      return id(weather_temp).state.c_str();
                    }
                    return "N/A";
              
              - label:
                  id: lbl_weather_condition
                  align: BOTTOM_MID
                  x: 0
                  y: -5
                  text_color: 0x000000
                  text: !lambda |-
                    if (!id(weather_condition).state.empty()) {
                      return id(weather_condition).state.c_str();
                    }
                    return "Unknown";

        # Location Section (below weather)
        - obj:
            id: location_container
            width: 320
            height: 130
            align: TOP_MID
            x: 0
            y: 245
            bg_color: 0xFFFFFF
            border_width: 3
            border_color: 0x000000
            pad_all: 10
            widgets:
              - label:
                  id: lbl_location_city
                  align: TOP_LEFT
                  x: 5
                  y: 5
                  text_color: 0x000000
                  text: !lambda |-
                    if (!id(location_city).state.empty() && !id(location_state).state.empty()) {
                      static char buf[64];
                      snprintf(buf, sizeof(buf), "%s, %s", 
                        id(location_city).state.c_str(), 
                        id(location_state).state.c_str());
                      return buf;
                    }
                    return "";
              
              - label:
                  id: lbl_latitude
                  align: TOP_LEFT
                  x: 5
                  y: 40
                  text_color: 0x000000
                  text: !lambda |-
                    if (!isnan(id(location_latitude).state)) {
                      static char buf[48];
                      float lat = id(location_latitude).state;
                      char dir = lat >= 0 ? 'N' : 'S';
                      lat = abs(lat);
                      int deg = (int)lat;
                      float min_float = (lat - deg) * 60;
                      int min = (int)min_float;
                      int sec = (int)((min_float - min) * 60);
                      snprintf(buf, sizeof(buf), "%d° %d' %d\" %c", deg, min, sec, dir);
                      return buf;
                    }
                    return "";
              
              - label:
                  id: lbl_longitude
                  align: TOP_LEFT
                  x: 5
                  y: 70
                  text_color: 0x000000
                  text: !lambda |-
                    if (!isnan(id(location_longitude).state)) {
                      static char buf[48];
                      float lon = id(location_longitude).state;
                      char dir = lon >= 0 ? 'E' : 'W';
                      lon = abs(lon);
                      int deg = (int)lon;
                      float min_float = (lon - deg) * 60;
                      int min = (int)min_float;
                      int sec = (int)((min_float - min) * 60);
                      snprintf(buf, sizeof(buf), "%d° %d' %d\" %c", deg, min, sec, dir);
                      return buf;
                    }
                    return "";

        # Fuel Level Arc
        - arc:
            id: arc_fuel
            x: 30
            y: 390
            start_angle: 135
            end_angle: 45
            rotation: 0
            min_value: 0
            max_value: 100
            value: 75
            widgets:
              - label:
                  align: CENTER
                  text: !lambda |-
                    static char buf[16];
                    snprintf(buf, sizeof(buf), "%.0f%%", id(fuel_level).state);
                    return buf;
              - label:
                  align: BOTTOM_MID
                  y: 25
                  text: "Fuel"

        # DEF Level Arc
        - arc:
            id: arc_def
            x: 210
            y: 390
            width: 150
            height: 150
            start_angle: 135
            end_angle: 45
            rotation: 0
            min_value: 0
            max_value: 100
            value: 50
            arc_width: 18
            arc_color: 0x000000
            arc_rounded: true
            indicator:
              arc_color: 0xFFFFFF
              arc_width: 18
            widgets:
              - label:
                  align: CENTER
                  text: !lambda |-
                    static char buf[16];
                    snprintf(buf, sizeof(buf), "%.0f%%", id(def_level).state);
                    return buf;
              - label:
                  align: BOTTOM_MID
                  y: 25
                  text: "DEF"

        # Battery Level Arc
        - arc:
            id: arc_battery
            x: 390
            y: 390
            width: 150
            height: 150
            start_angle: 135
            end_angle: 45
            rotation: 0
            min_value: 0
            max_value: 100
            value: 90
            arc_width: 18
            arc_color: 0x000000
            arc_rounded: false
            indicator:
              arc_color: 0xFFFFFF
              arc_width: 18
            widgets:
              - label:
                  align: CENTER
                  text: !lambda |-
                    static char buf[16];
                    snprintf(buf, sizeof(buf), "%.0f%%", id(vehicle_battery).state);
                    return buf;
              - label:
                  align: BOTTOM_MID
                  y: 25
                  text: "Battery"

# Deep sleep configuration - https://esphome.io/components/deep_sleep/
deep_sleep:
  id: deep_sleep_id
  sleep_duration: ${sleep_duration}
  wakeup_pin:
    number: GPIO3
    ignore_strapping_warning: true

sensor:
  - platform: template
    name: "Wakeup Cause"
    accuracy_decimals: 0
    lambda: return esp_sleep_get_wakeup_cause();

  - platform: homeassistant
    id: location_latitude
    entity_id: sensor.location_latitude

  - platform: homeassistant
    id: location_longitude
    entity_id: sensor.location_longitude

  - platform: homeassistant
    id: fuel_level
    entity_id: sensor.fuel_level
    on_value:
      then:
        - lvgl.arc.update:
            id: arc_fuel
            value: !lambda return x;

  - platform: homeassistant
    id: def_level
    entity_id: sensor.def_level
    on_value:
      then:
        - lvgl.arc.update:
            id: arc_def
            value: !lambda return x;

  - platform: homeassistant
    id: vehicle_battery
    entity_id: sensor.vehicle_battery
    on_value:
      then:
        - lvgl.arc.update:
            id: arc_battery
            value: !lambda return x;

display:
  - id: !extend epaper_display
    auto_clear_enabled: false
    update_interval: never

# Home Assistant sensors for dashboard
text_sensor:
  - platform: homeassistant
    id: weather_condition
    entity_id: weather.forecast_home
    attribute: condition
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_weather_icon
            text: !lambda |-
              std::map<std::string, std::string> weather_icons = {
                {"clear-night", "\U000F0594"},
                {"cloudy", "\U000F0590"},
                {"exceptional", "\U000F0F2F"},
                {"fog", "\U000F0591"},
                {"hail", "\U000F0592"},
                {"lightning", "\U000F0593"},
                {"lightning-rainy", "\U000F067E"},
                {"partlycloudy", "\U000F0595"},
                {"pouring", "\U000F0596"},
                {"rainy", "\U000F0597"},
                {"snowy", "\U000F0598"},
                {"snowy-rainy", "\U000F067F"},
                {"sunny", "\U000F0599"},
                {"windy", "\U000F059D"},
                {"windy-variant", "\U000F059E"}
              };
              std::string condition = x;
              return weather_icons.count(condition) ? weather_icons[condition].c_str() : "\U000F14E4";

  - platform: homeassistant
    id: weather_temp
    entity_id: weather.forecast_home
    attribute: temperature

  - platform: homeassistant
    id: location_city
    entity_id: sensor.location_city

  - platform: homeassistant
    id: location_state
    entity_id: sensor.location_state
