# https://jnan.co/tools/esphomelvglsim/

# Dashboard to display home assistant status and weather information.

# https://wikitwist.com/how-to-use-the-seeedstudio-reterminal-e1001-with-home-assistant-via-esphome/
# https://wiki.seeedstudio.com/reterminal_e10xx_with_esphome/
# https://wiki.seeedstudio.com/reterminal_e10xx_with_esphome_advanced/

substitutions:
  device_name: terminal
  friendly_name: "Terminal Display"
  project_version: "1.0.0"
  log_level: VERBOSE
  sleep_duration: 10min

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
      - path: packages/icons/network_icons.yaml
      - path: packages/icons/battery_icons.yaml
      - path: packages/icons/weather_icons.yaml
      - path: packages/icons/homeassistant_icons.yaml
      - path: devices/reterminal-e1001.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  on_boot:
    then:
      - logger.log: "esphome on_boot"
      - output.turn_on: bsp_battery_enable
      - delay: 150ms
      - component.update: battery_voltage
      - component.update: battery_level
      - lvgl.resume:
      - lambda: |-
          ESP_LOGI("esphome", "ESPHomme on_boot triggered");

image:
  - file: mdi:sun-wireless-outline
    type: BINARY
    id: solar_power_icon
    resize: 50x50

  - file: mdi:alert-outline
    type: binary
    id: alert
    resize: 80x80

binary_sensor:
  - id: !extend button_left
    on_press:
      then:
        - lvgl.page.previous:
            time: 0ms

  - id: !extend button_right
    on_press:
      then:
        - lvgl.page.next:
            time: 0ms

  - id: !remove button_green

interval:
  - interval: 10min
    then:
      - logger.log: "Update display interval"
      - component.update: epaper_display

lvgl:
  color_depth: 16
  bg_color: 0
  border_width: 0
  outline_width: 0
  shadow_width: 0
  text_font: unscii_16
  align: center

  on_idle:
    timeout: 10s
    then:
      - logger.log: "LVGL on_idle"
      - lambda: |-
          ESP_LOGI("display", "on_idle");
  
  on_ready:
    then:
      - logger.log: "LVGL on_ready"
      - lambda: |-
          ESP_LOGI("display", "on_ready");

  on_draw_start:
    - logger.log: "LVGL on_draw_start"
    - lambda: |-
        ESP_LOGI("display", "on_draw_start");

  on_draw_end:
    - logger.log: "LVGL on_draw_end"
    - lambda: |-
        ESP_LOGI("display", "on_draw_end");
    - component.update: epaper_display

  on_pause:
    - logger.log: "LVGL on_pause"
    - lambda: |-
        ESP_LOGI("display", "on_pause");
    - deep_sleep.enter:
        id: deep_sleep_id
        sleep_duration: ${sleep_duration}

  on_resume:
    - logger.log: "LVGL on_resume"
  on_boot:
    - logger.log: "LVGL on_boot"

  widgets:
    # Header container spanning the top of the display
    - obj:
        id: header_container
        width: 100%
        height: 40
        align: TOP_LEFT
        x: 0
        y: 0
        bg_color: 0x000000
        border_width: 0
        pad_all: 5
        widgets:
          # WiFi status (right side, leftmost)
          - label:
              id: lbl_wifi_status
              align: TOP_LEFT
              x: 120
              y: 5
              text_font: wifi_icons
              text: !lambda |-
                std::string icon;

                if (WiFi.isConnected())
                {
                  if (!isnan(id(wifi_rssi).state))
                  {
                    float r = id(wifi_rssi).state;
                    if      (r > -55) icon = "\U000F0928"; // wifi-strength-4
                    else if (r > -65) icon = "\U000F0925"; // wifi-strength-3
                    else if (r > -72) icon = "\U000F0922"; // wifi-strength-2
                    else if (r > -80) icon = "\U000F091F"; // wifi-strength-1
                    else              icon = "\U000F091F"; // wifi-strength-0
                  }
                }
                else
                {
                  icon = "";
                }
 
                char buf[8];
                snprintf(buf, sizeof(buf), "%s", icon.c_str());
                return buf;

          # Home Assistant status (right side, second from left)
          - label:
              id: lbl_ha_status
              align: TOP_LEFT
              x: 90
              y: 5
              text_font: homeassistant_icons
              text: !lambda |-
                if (id(ha_connected).state) {
                  ESP_LOGI("ha", "Connected to Home Assistant");
                  return "\U000F07D0";
                } else {
                  ESP_LOGW("ha", "NOT connected to Home Assistant");
                  return "\U000F0028";
                }

          # Battery power cord (right side, second from right)
          - label:
              id: lbl_battery_power_cord
              align: TOP_LEFT
              x: 40
              y: 5
              text: "⚡"
              text_font: battery_icons
              hidden: true  # Initially hidden
              
          # Battery status (rightmost)
          - label:
              id: lbl_battery_status
              align: TOP_LEFT
              x: 10
              y: 5
              text_font: battery_icons
              text: !lambda |-
                static char buf[10];
                std::string icon;
                int x = id(battery_level).state;
                if (x == 100.0) {
                  icon = "\U000F0079"; // mdi-battery (full)
                } else if (x > 90) {
                  icon = "\U000F0082"; // mdi-battery-90
                } else if (x > 80) {
                  icon = "\U000F0081"; // mdi-battery-80
                } else if (x > 70) {
                  icon = "\U000F0080"; // mdi-battery-70
                } else if (x > 60) {
                  icon = "\U000F007F"; // mdi-battery-60
                } else if (x > 50) {
                  icon = "\U000F007E"; // mdi-battery-50
                } else if (x > 40) {
                  icon = "\U000F007D"; // mdi-battery-40
                } else if (x > 30) {
                  icon = "\U000F007C"; // mdi-battery-30
                } else if (x > 20) {
                  icon = "\U000F007B"; // mdi-battery-20
                } else if (x > 10) {
                  icon = "\U000F007A"; // mdi-battery-10
                } else if (x > 0) {
                  icon = "\U000F008E"; // mdi-battery-outline
                } else {
                  icon = "\U000F0091"; // mdi-battery-unknown
                }
                snprintf(buf, sizeof(buf), "%s", icon.c_str());
                return buf;

#          - label:
#              id: lbl_battery_level
#              align: TOP_LEFT
#              x: 10
#              y: 5
#              text: !lambda |-
#                int level = (int)(id(battery_level).state + 0.5f);
#                static char buf[10];
#                snprintf(buf, sizeof(buf), "%d%%", level);
#                return buf;

# Deep sleep configuration - https://esphome.io/components/deep_sleep/
deep_sleep:
  id: deep_sleep_id
  sleep_duration: ${sleep_duration}
  wakeup_pin: GPIO3

sensor:
  - platform: template
    name: "Wakeup Cause"
    accuracy_decimals: 0
    lambda: return esp_sleep_get_wakeup_cause();

display:
  - id: !extend epaper_display
    auto_clear_enabled: false
    update_interval: never
