# Minimal ESP32-P4 test - no display, no WiFi, just boot and blink
substitutions:
  device_name: esp32-p4-test
  friendly_name: ESP32-P4 Test

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-p4-evboard
  variant: esp32p4
  flash_size: 16MB
  framework:
    type: esp-idf

# ESP32-C6 co-processor for WiFi via SDIO
esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

# Flash C6 firmware from local binary (no network needed for first boot)
update:
  - platform: esp32_hosted
    name: "ESP32-C6 Firmware"
    type: embedded
    path: network_adapter_esp32c6.bin
    sha256: 2aa46dbcd18f5b2046f58b82cdc62bdf21af137930e67c4b3b114f6e3e0daf15

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  platform: esphome

logger:
  level: DEBUG
  hardware_uart: UART0

# Just a simple interval to prove it boots
interval:
  - interval: 1s
    then:
      - lambda: |-
          ESP_LOGI("test", "ESP32-P4 is alive!");
