# Espar Airtronic AS3 D2L Diesel Heater - CAN Bus Controller
# Hardware: Seeed Studio XIAO ESP32-S3 + CAN Bus Breakout Board (MCP2515 + SN65HVD230)
# https://wiki.seeedstudio.com/xiao-can-bus-expansion/
#
# Wiring:
#   XIAO CAN Bus Breakout Board plugs directly onto the XIAO ESP32-S3.
#   Connect CAN-H and CAN-L terminals to the Espar heater's CAN bus lines.
#   If CAN communication fails, short the P1 pad on the back of the breakout
#   board to enable the 120 ohm termination resistor.
#
# IMPORTANT - Before using commands:
#   1. Start with sniff_mode: "true" to discover CAN IDs on your heater
#   2. Monitor logs to identify the status broadcast and command IDs
#   3. Update the can_id substitutions below with your discovered values
#   4. Set sniff_mode: "false" to switch to normal operation
#
# The Espar AS3 D2L CAN bus protocol is proprietary. The CAN IDs and data byte
# assignments below are typical starting points based on community findings.
# Your specific heater firmware version may differ - always verify by sniffing first.

substitutions:
  device_name: esparheater
  friendly_name: Espar Heater
  project_name: Van Espar Heater Controller
  project_version: "1.0.1"
  log_level: DEBUG

  # --- CAN Bus Configuration ---
  # Set to "true" to log ALL CAN frames (discovery mode)
  # Set to "false" for normal operation with parsed sensors
  sniff_mode: "true"

  # CAN bus bit rate - Espar AS3 typically uses 25kbps
  # If no frames appear, try: 10kbps, 20kbps, 50kbps, 100kbps
  can_bit_rate: 25kbps

  # MCP2515 crystal frequency (8MHz on the Seeed breakout board)
  mcp_clock: 8MHZ

  # --- Espar CAN IDs (update after sniffing your heater) ---
  # These are placeholder IDs - replace with values discovered from your heater
  heater_status_id: "0x100"       # Heater -> Controller: status broadcast
  heater_temp_id: "0x101"         # Heater -> Controller: temperature data
  heater_error_id: "0x102"        # Heater -> Controller: error/diagnostic data
  heater_command_id: "0x620"      # Controller -> Heater: commands

# --- Packages (remote with variable overrides) ---
packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
      - path: devices/xiao-esp32s3.yaml
      - path: packages/ota/http_update.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: smartvan.${project_name}
    version: ${project_version}
  on_boot:
    priority: 600
    then:
      - lambda: |-
          ESP_LOGI("espar", "Espar Heater CAN Bus Controller booted");
          ESP_LOGI("espar", "Sniff mode: ${sniff_mode}");
          ESP_LOGI("espar", "CAN bit rate: ${can_bit_rate}");

# Enable web server for debugging
web_server:
  port: 80

# --- SPI Bus (XIAO ESP32-S3 default SPI pins) ---
spi:
  clk_pin: GPIO7    # D8
  miso_pin: GPIO8   # D9
  mosi_pin: GPIO9   # D10

# --- CAN Bus (MCP2515 on Seeed CAN Bus Breakout Board) ---
canbus:
  - platform: mcp2515
    id: espar_can
    cs_pin: GPIO44   # D7 - CS pin on the CAN Bus Breakout Board
    clock: ${mcp_clock}
    can_id: 0
    bit_rate: ${can_bit_rate}
    on_frame:
      # ---------------------------------------------------------------
      # SNIFF MODE: Log all CAN frames for protocol discovery
      # ---------------------------------------------------------------
      - can_id: 0
        can_id_mask: 0          # Match ALL CAN IDs
        then:
          - lambda: |-
              // Always log in sniff mode, skip in normal mode
              if (std::string("${sniff_mode}") != "true") return;

              // Format data bytes as hex string
              std::string data_hex = "";
              for (size_t i = 0; i < x.size(); i++) {
                char buf[4];
                snprintf(buf, sizeof(buf), "%02X ", x[i]);
                data_hex += buf;
              }
              ESP_LOGI("espar_sniff", "CAN ID: 0x%03X  Len: %d  Data: %s",
                can_id, x.size(), data_hex.c_str());

      # ---------------------------------------------------------------
      # HEATER STATUS: Parse status broadcast frame
      # Update the can_id below after sniffing your heater
      # ---------------------------------------------------------------
      - can_id: ${heater_status_id}
        then:
          - lambda: |-
              if (std::string("${sniff_mode}") == "true") return;
              if (x.size() < 8) return;

              // --- Typical status frame byte assignments ---
              // NOTE: These are EXAMPLES - verify against your sniffed data!
              // Byte 0: Heater operating state
              //   0x00 = Off
              //   0x01 = Starting (glow plug preheat)
              //   0x02 = Starting (fuel priming)
              //   0x03 = Ignition
              //   0x04 = Running / Heating
              //   0x05 = Cooldown / Shutdown
              //   0x06 = Error / Lockout
              uint8_t state = x[0];

              const char* state_str;
              switch (state) {
                case 0x00: state_str = "Off"; break;
                case 0x01: state_str = "Glow Plug Preheat"; break;
                case 0x02: state_str = "Fuel Priming"; break;
                case 0x03: state_str = "Ignition"; break;
                case 0x04: state_str = "Running"; break;
                case 0x05: state_str = "Cooldown"; break;
                case 0x06: state_str = "Error"; break;
                default: state_str = "Unknown"; break;
              }

              ESP_LOGI("espar", "Heater state: %s (0x%02X)", state_str, state);
              id(heater_state).publish_state(state_str);
              id(heater_running).publish_state(state == 0x04);

              // Byte 1: Heat output level / power percentage
              if (x.size() > 1) {
                float power_pct = (float)x[1] / 255.0 * 100.0;
                id(heater_power).publish_state(power_pct);
              }

              // Byte 2-3: Fan speed (RPM, big-endian)
              if (x.size() > 3) {
                uint16_t fan_rpm = (x[2] << 8) | x[3];
                id(heater_fan_speed).publish_state(fan_rpm);
              }

      # ---------------------------------------------------------------
      # HEATER TEMPERATURE: Parse temperature data frame
      # ---------------------------------------------------------------
      - can_id: ${heater_temp_id}
        then:
          - lambda: |-
              if (std::string("${sniff_mode}") == "true") return;
              if (x.size() < 4) return;

              // Byte 0-1: Exhaust temperature (°C * 10, big-endian)
              int16_t exhaust_raw = (x[0] << 8) | x[1];
              float exhaust_temp = exhaust_raw / 10.0;
              id(heater_exhaust_temp).publish_state(exhaust_temp);

              // Byte 2-3: Supply voltage (mV, big-endian)
              if (x.size() > 3) {
                uint16_t voltage_mv = (x[2] << 8) | x[3];
                float voltage = voltage_mv / 1000.0;
                id(heater_voltage).publish_state(voltage);
              }

              ESP_LOGD("espar", "Exhaust: %.1f°C  Supply: %.1fV",
                exhaust_temp, (x.size() > 3) ? ((x[2] << 8) | x[3]) / 1000.0 : 0.0);

      # ---------------------------------------------------------------
      # HEATER ERRORS: Parse diagnostic/error frame
      # ---------------------------------------------------------------
      - can_id: ${heater_error_id}
        then:
          - lambda: |-
              if (std::string("${sniff_mode}") == "true") return;
              if (x.size() < 2) return;

              uint16_t error_code = (x[0] << 8) | x[1];
              if (error_code != 0) {
                ESP_LOGW("espar", "Heater error code: %d (0x%04X)", error_code, error_code);
              }
              id(heater_error_code).publish_state(error_code);

# --- Sensors ---
sensor:
  - platform: template
    name: "${friendly_name} Exhaust Temperature"
    id: heater_exhaust_temp
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    icon: mdi:thermometer-high

  - platform: template
    name: "${friendly_name} Supply Voltage"
    id: heater_voltage
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    icon: mdi:car-battery

  - platform: template
    name: "${friendly_name} Fan Speed"
    id: heater_fan_speed
    unit_of_measurement: "RPM"
    state_class: measurement
    accuracy_decimals: 0
    icon: mdi:fan

  - platform: template
    name: "${friendly_name} Power Level"
    id: heater_power
    unit_of_measurement: "%"
    state_class: measurement
    accuracy_decimals: 0
    icon: mdi:fire

  - platform: template
    name: "${friendly_name} Error Code"
    id: heater_error_code
    accuracy_decimals: 0
    icon: mdi:alert-circle

# --- Text Sensors ---
text_sensor:
  - platform: template
    name: "${friendly_name} State"
    id: heater_state
    icon: mdi:radiator

# --- Binary Sensors ---
binary_sensor:
  - platform: template
    name: "${friendly_name} Running"
    id: heater_running
    device_class: running
    icon: mdi:fire-circle

# --- Controls ---
switch:
  - platform: template
    name: "${friendly_name} Power"
    id: heater_switch
    icon: mdi:radiator
    optimistic: true
    turn_on_action:
      - logger.log: "Sending heater START command"
      - canbus.send:
          canbus_id: espar_can
          can_id: ${heater_command_id}
          data: [0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    turn_off_action:
      - logger.log: "Sending heater STOP command"
      - canbus.send:
          canbus_id: espar_can
          can_id: ${heater_command_id}
          data: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

# --- Buttons ---
button:
  - platform: template
    name: "${friendly_name} Start"
    icon: mdi:play
    on_press:
      - logger.log: "Sending heater START command"
      - canbus.send:
          canbus_id: espar_can
          can_id: ${heater_command_id}
          data: [0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

  - platform: template
    name: "${friendly_name} Stop"
    icon: mdi:stop
    on_press:
      - logger.log: "Sending heater STOP command"
      - canbus.send:
          canbus_id: espar_can
          can_id: ${heater_command_id}
          data: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

# --- Number: Heat level adjustment ---
number:
  - platform: template
    name: "${friendly_name} Heat Level"
    id: heater_heat_level
    icon: mdi:thermometer-lines
    min_value: 0
    max_value: 100
    step: 10
    initial_value: 0
    optimistic: true
    unit_of_measurement: "%"
    set_action:
      - logger.log:
          format: "Setting heater level to %.0f%%"
          args: ['x']
      - canbus.send:
          canbus_id: espar_can
          can_id: ${heater_command_id}
          data: !lambda |-
            uint8_t level = (uint8_t)(x * 255.0 / 100.0);
            return {0x02, level, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

# --- Climate: Thin wrapper that forwards mode/setpoint to the CAN bus ---
# The heater has its own thermostat - this just sends commands when you
# change mode or target temperature from the HA UI.
climate:
  - platform: thermostat
    name: "${friendly_name} Climate"
    id: heater_climate
    icon: mdi:radiator
    sensor: heater_exhaust_temp  # Display-only; the heater controls its own loop
    visual:
      min_temperature: 10
      max_temperature: 35
      temperature_step: 1.0
    min_idle_time: 10s
    min_heating_off_time: 60s     # Prevent rapid cycling - heater needs cooldown
    min_heating_run_time: 120s    # Let heater run at least 2 min per cycle
    heat_deadband: 0.5
    heat_overrun: 0.5
    heat_action:
      - lambda: |-
          if (std::string("${sniff_mode}") == "true") {
            ESP_LOGW("espar", "Sniff mode active - not sending heat command");
            return;
          }
          float setpoint = id(heater_climate).target_temperature;
          uint8_t temp_byte = (uint8_t)clamp((int)setpoint, 0, 255);
          ESP_LOGI("espar", "Climate HEAT: sending start + setpoint %.0f°C", setpoint);
      - if:
          condition:
            lambda: 'return std::string("${sniff_mode}") != "true";'
          then:
            - canbus.send:
                canbus_id: espar_can
                can_id: ${heater_command_id}
                data: !lambda |-
                  float setpoint = id(heater_climate).target_temperature;
                  uint8_t temp_byte = (uint8_t)clamp((int)setpoint, 0, 255);
                  return {0x01, temp_byte, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    idle_action:
      - lambda: |-
          if (std::string("${sniff_mode}") == "true") {
            ESP_LOGW("espar", "Sniff mode active - not sending idle/off command");
            return;
          }
          ESP_LOGI("espar", "Climate IDLE: sending stop command");
      - if:
          condition:
            lambda: 'return std::string("${sniff_mode}") != "true";'
          then:
            - canbus.send:
                canbus_id: espar_can
                can_id: ${heater_command_id}
                data: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    off_mode:
      - lambda: 'ESP_LOGI("espar", "Climate mode set to OFF");'
    heat_mode:
      - lambda: 'ESP_LOGI("espar", "Climate mode set to HEAT");'
    target_temperature_change_action:
      - lambda: |-
          if (std::string("${sniff_mode}") == "true") return;
          float setpoint = id(heater_climate).target_temperature;
          ESP_LOGI("espar", "Target temperature changed to %.0f°C", setpoint);
      - if:
          condition:
            lambda: 'return std::string("${sniff_mode}") != "true";'
          then:
            - canbus.send:
                canbus_id: espar_can
                can_id: ${heater_command_id}
                data: !lambda |-
                  float setpoint = id(heater_climate).target_temperature;
                  uint8_t temp_byte = (uint8_t)clamp((int)setpoint, 0, 255);
                  return {0x02, temp_byte, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 20
