# Template for a dial controller using ESP32 with a rotary encoder and display.

# pushing the button will toggle the current device on/off.
# rotating the dial will adjust a value (e.g., brightness).
# pressing and holding the button for 2 seconds will turn the device off.
# swiping left and right will switch between the lights
# automatically turn off the display after a period of inactivity.

# I can do this either in esphome manually or via home assistant by creating a target knob.
# the question is if home assistant should have the concept - I think that we want it on the knob
# to be able to rotate through the different devices. 




substitutions:
  device_name: light-dial-controller
  friendly_name: Light Dial Controller
  project_name: Light Dial Controller
  project_version: "1.0.0"

packages:
  - !include
    file: packages/home_assistant_light.yaml
    vars:
      light_id: rear_can_lights
      entity_id: light.rear_can_lights
  - !include packages/common.yaml
  - !include packages/network/wifi.yaml
  - !include packages/time/homeassistant.yaml
  - !include packages/display/sleep.yaml
  - !include devices/viewe-esp32c3-rotary-knob.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}
  on_boot:
    then:
      - logger.log: "Light Dial Controller booted."

globals:
  - id: current_brightness
    type: int
    restore_value: yes
    initial_value: '0'

  - id: selected_idx
    type: int
    restore_value: yes
    initial_value: '0'   # 0..N-1

select:
  - platform: template
    id: device_select
    name: "Selected Device"
    optimistic: true
    options:
      - "All Lights"
      - "Front Can Lights"
      - "Bed Can Lights"
      - "Capsule Lights" # driver and passenger areas
      - "Exterior Lights"
    set_action:
      - lambda: |-
          auto s = id(device_select).state;
          if (s == "All Lights") { id(selected_idx) = 0; }
          else if (s == "Front Can Lights")   { id(selected_idx) = 1; }
          else if (s == "Bed Can Lights")   { id(selected_idx) = 2; }
          else if (s == "Capsule Lights")   { id(selected_idx) = 3; }
          else if (s == "Exterior Lights")   { id(selected_idx) = 4; }
      - script.execute: sync_from_ha_for_selected


script:
  - id: publish_brightness
    then:
      - homeassistant.service:
          service: light.turn_on
          data:
            entity_id: light.rear_can_lights
            brightness_pct: !lambda 'return (int)id(current_brightness);'


sensor:
  - platform: homeassistant
    id: br_lr_raw
    entity_id: light.living_room         # <-- CHANGE
    attribute: brightness

  - platform: homeassistant
    id: br_desk_raw
    entity_id: light.desk                # <-- CHANGE
    attribute: brightness

  - platform: homeassistant
    id: br_lamp_raw
    entity_id: light.bedside_lamp        # <-- CHANGE
    attribute: brightness

# (Optional) expose local brightness for visibility
number:
  - platform: template
    id: local_brightness_pct
    name: "Knob Brightness (Local %)"
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          id(current_brightness) = (int)x;
      - script.execute: publish_brightness_immediate
    lambda: |-
      return id(current_brightness);

# -------------------- Rotary & button --------------------
sensor:
  - platform: rotary_encoder
    id: knob_encoder
    name: "Knob Encoder"
    pin_a: GPIO4          # <-- set to your pins
    pin_b: GPIO5
    resolution: 2
    on_clockwise:
      then:
        - lambda: |-
            int step = 2;
            id(current_brightness) = std::min(100, id(current_brightness) + step);
        - script.execute: publish_brightness_throttled
    on_anticlockwise:
      then:
        - lambda: |-
            int step = 2;
            id(current_brightness) = std::max(0, id(current_brightness) - step);
        - script.execute: publish_brightness_throttled

binary_sensor:
  - platform: gpio
    id: knob_button
    name: "Knob Button"
    pin:
      number: GPIO9                      # <-- your button pin
      mode:
        input: true
        pullup: true
    inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

    on_click:
      # Short: toggle selected light
      - min_length: 50ms
        max_length: 400ms
        then:
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: !lambda |-
                  static const char* ENTITIES[] = {
                    "light.living_room", "light.desk", "light.bedside_lamp"   // <-- CHANGE
                  };
                  int i = std::max(0, std::min(2, id(selected_idx)));
                  return std::string(ENTITIES[i]);

      # Long: next device
      - min_length: 800ms
        max_length: 10s
        then:
          - lambda: |-
              id(selected_idx) = (id(selected_idx) + 1) % 3;   // wrap 0..2
          - script.execute: sync_from_ha_for_selected
          - logger.log:
              format: "Switched to index %d"
              args: [ 'id(selected_idx)' ]

# -------------------- Scripts --------------------
script:
  # Pull brightness from HA for whichever device is selected
  - id: sync_from_ha_for_selected
    mode: restart
    then:
      - lambda: |-
          int i = std::max(0, std::min(2, id(selected_idx)));
          float raw = NAN;
          switch (i) {
            case 0: raw = id(br_lr_raw).state;  break;
            case 1: raw = id(br_desk_raw).state; break;
            case 2: raw = id(br_lamp_raw).state; break;
          }
          if (!isnan(raw)) {
            id(current_brightness) = (int) roundf((raw / 255.0f) * 100.0f);
          }

  # Coalesce rapid knob ticks
  - id: publish_brightness_throttled
    mode: restart
    then:
      - delay: 120ms
      - script.execute: publish_brightness_immediate

  # Publish to the selected entity
  - id: publish_brightness_immediate
    mode: queued
    then:
      - lambda: |-
          id(current_brightness) = std::max(0, std::min(100, id(current_brightness)));
      - homeassistant.service:
          service: light.turn_on
          data:
            entity_id: !lambda |-
              static const char* ENTITIES[] = {
                "light.living_room", "light.desk", "light.bedside_lamp"      # <-- CHANGE
              };
              int i = std::max(0, std::min(2, id(selected_idx)));
              return std::string(ENTITIES[i]);
            brightness_pct: !lambda 'return
