# Template for a dial controller using ESP32 with a rotary encoder and display.

# pushing the button will toggle the current device on/off.
# rotating the dial will adjust a value (e.g., brightness).
# pressing and holding the button for 2 seconds will turn the device off.
# swiping left and right will switch between the lights
# automatically turn off the display after a period of inactivity.

# I can do this either in esphome manually or via home assistant by creating a target knob.
# the question is if home assistant should have the concept - I think that we want it on the knob
# to be able to rotate through the different devices. 

substitutions:
  device_name: light-dial-controller
  friendly_name: Light Dial Controller
  project_version: "1.0.0"

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
      - path: packages/display/sleep.yaml
        vars:
          backlight_light_id: display_backlight_id
          inactivity_timeout: 300s
      - path: packages/home_assistant_light.yaml
        vars:
          light_id: rear_can_lights
          entity_id: light.rear_can_lights
      - path: devices/viewe-esp32c3-rotary-knob.yaml

sensor:
  - id: !extend knob_encoder_id
    name: "Knob Encoder"
    on_clockwise:
      then:
        - lambda: |-
            int step = 2;
            id(current_brightness) = std::min(100, id(current_brightness) + step);
        - script.execute: publish_brightness_throttled

    on_anticlockwise:
      then:
        - lambda: |-
            int step = 2;
            id(current_brightness) = std::max(0, id(current_brightness) - step);
        - script.execute: publish_brightness_throttled

binary_sensor:
  - id: !extend encoder_button_id
    on_multi_click:
      # Single click
      - timing:
          - ON for at most 500ms
          - OFF for at least 100ms
        then:
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: !lambda |-
                  static const char* ENTITIES[] = {
                    "light.living_room", "light.desk", "light.bedside_lamp"   // <-- CHANGE
                  };
                  int i = std::max(0, std::min(2, id(selected_idx)));
                  return std::string(ENTITIES[i]);

      # Double click
      - timing:
          - ON for at most 500ms
          - OFF for at most 500ms
          - ON for at most 500ms
          - OFF for at least 100ms
        then:
          - logger.log: "Double click detected - no action assigned"

      # Long press
      - timing:
          - ON for at least 1000ms
        then:
          - logger.log: "Long press detected - no action assigned"