# Template for a dial controller using ESP32 with a rotary encoder and display.

# pushing the button will toggle the current device on/off.
# rotating the dial will adjust a value (e.g., brightness).
# pressing and holding the button for 2 seconds will turn the device off.
# automatically turn off the display after a period of inactivity.

substitutions:
  device_name: light_dial_controller
  friendly_name: Light Dial Controller
  project_version: "1.0.0"

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
      - path: packages/display/sleep.yaml
        vars:
          display_id: round_display
          display_panel_power_switch_id: display_backlight_id
      - path: devices/viewe-esp32c3-rotary-knob.yaml
      - path: packages/icons/network_icons.yaml
      - path: packages/icons/weather_icons.yaml
      - path: packages/icons/battery_icons.yaml
      - path: packages/icons/homeassistant_icons.yaml

#      - path: packages/home_assistant_light.yaml
#        vars:
#          light_id: rear_can_lights
#          entity_id: light.rear_can_lights

font:
  - file: "gfonts://Roboto"
    id: roboto_16
    size: 16
    glyphs: "!%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"
  - file: "gfonts://Roboto"
    id: roboto_24
    size: 24
    glyphs: "!%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"

number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 60
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box

lvgl:
# https://esphome.io/cookbook/lvgl/#turn-off-screen-when-idle
  on_idle:
    timeout: !lambda "return (id(display_timeout).state * 1000);"
    then:
      - logger.log: "LVGL is idle"
      - light.turn_off: display_backlight_id
      - lvgl.pause:

  disp_bg_color: 0x000000

  top_layer:
    widgets:
      # WiFi signal strength indicator (top-left)
      - label:
          id: wifi_icon
          align: TOP_LEFT
          x: 5
          y: 5
          text: "\U000F05A9"  # mdi:wifi
          text_font: battery_icons
          text_color: 0xFFFFFF
      - label:
          id: wifi_signal_label
          align: TOP_LEFT
          x: 25
          y: 5
          text: "-"
          text_font: roboto_16
          text_color: 0x00FF00
      
      # Home Assistant connection status (top-right)
      - label:
          id: ha_status_icon
          align: TOP_RIGHT
          x: -25
          y: 5
          text: "\U000F02DC"  # mdi:home
          text_font: battery_icons
          text_color: 0xFFFFFF
      - label:
          id: ha_connection_label
          align: TOP_RIGHT
          x: -5
          y: 5
          text: "?"
          text_font: roboto_16
          text_color: 0xFFFF00

  pages:
    - id: main_page
      widgets:
        # Circular arc showing brightness level (0-100%)
        - arc:
            id: brightness_arc
            align: CENTER
            x: 0
            y: 0
            width: 180
            height: 180
            arc_color: 0x444444
            arc_width: 12
            min_value: 0
            max_value: 100
            value: 0
            adjustable: false
            bg_color: 0x222222
            bg_opa: COVER
            radius: 90
            indicator:
              arc_color: 0xFFDD44
              arc_width: 14

        # Light icon (centered, above name)
        - label:
            id: light_icon_label
            align: CENTER
            x: 0
            y: -35
            text: "💡"
            text_font: roboto_24
            text_color: 0xFFFFFF

        # Light name (centered)
        - label:
            id: light_name_label
            align: CENTER
            x: 0
            y: 10
            text: "Living Room"
            text_font: roboto_16
            text_color: 0xFFFFFF

        # Brightness percentage (centered, below name)
        - label:
            id: brightness_pct_label
            align: CENTER
            x: 0
            y: 40
            text: "0%"
            text_font: roboto_24
            text_color: 0xFFDD44

select:
  - platform: template
    name: "Dial Selected Light"
    id: dial_selected_light
    initial_option: light.bed_interior_lights
    options:
      - light.bed_interior_lights
      - light.main_can_lights
      - light.bed_can_lights
      - light.cwww_led_capsule_lights
      - light.exterior_lights
      - light.door_light
      - light.cwww_led_dog_crate_lights

    set_action: # The action that should be performed when the remote (like Home Assistant’s frontend) requests to set the Select option
      - logger.log:
          format: "Selected light option (remote): %s (index %d)"
          args: ["x.c_str()", "i"]

    on_value:
      then:
        - logger.log:
            format: "Selected light option: %s (index %d)"
            args: ["x.c_str()", "i"]

globals:
  - id: current_brightness
    type: int
    initial_value: "0"

  - id: selected_light_index
    type: int
    initial_value: "0"
    restore_value: yes

  - id: selected_entity
    type: std::string
    initial_value: "light.living_room"
    restore_value: yes

script:
  - id: update_light_display
    then:
      - lambda: |-
          // before we update the lvgl widget, we need to ensure that current_brightness
          // we need to read the brightness of the currently selected light.
          auto index = id(dial_selected_light).active_index();
          if (index.has_value()) {

            auto selected_option = id(dial_selected_light).at(index.value());

            int brightness = 0;
            if (strcmp(selected_option.c_str(), "light.bed_interior_lights") == 0) {
                brightness = (int)roundf((id(light_bed_interior_lights_brightness).state / 255.0f) * 100.0f);
            } else if (strcmp(selected_option.c_str(), "light.main_can_lights") == 0) {
                brightness = (int)roundf((id(light_main_can_lights_brightness).state / 255.0f) * 100.0f);
            } else if (strcmp(selected_option.c_str(), "light.bed_can_lights") == 0) {
                brightness = (int)roundf((id(light_bed_can_lights_brightness).state / 255.0f) * 100.0f);
            } else if (strcmp(selected_option.c_str(), "light.cwww_led_capsule_lights") == 0) {
                brightness = (int)roundf((id(light_cwww_led_capsule_lights_brightness).state / 255.0f) * 100.0f);
            } else if (strcmp(selected_option.c_str(), "light.exterior_lights") == 0) {
                brightness = (int)roundf((id(light_exterior_lights_brightness).state / 255.0f) * 100.0f);
            } else if (strcmp(selected_option.c_str(), "light.door_light") == 0) {
                brightness = (int)roundf((id(light_door_light_brightness).state / 255.0f) * 100.0f);
            } else if (strcmp(selected_option.c_str(), "light.cwww_led_dog_crate_lights") == 0) {
                brightness = (int)roundf((id(light_cwww_led_dog_crate_lights_brightness).state / 255.0f) * 100.0f);
            } else {
                brightness = 0;
            }

            id(current_brightness) = brightness;
          }

          // Update LVGL widgets
          id(brightness_arc).set_value(id(current_brightness));
          char buf[8];
          snprintf(buf, sizeof(buf), "%d%%", id(current_brightness));
          id(brightness_pct_label).set_text(buf);

  - id: increase_light_brightness
    then:
      - lambda: |-
          int step = 2;
          id(current_brightness) = std::min(100, id(current_brightness) + step);
          id(publish_brightness_throttled).execute();

  - id: decrease_light_brightness
    then:
      - lambda: |-
          int step = 2;
          id(current_brightness) = std::max(0, id(current_brightness) - step);
          id(publish_brightness_throttled).execute();

  - id: publish_brightness_throttled
    mode: restart
    then:
      - delay: 300ms
      - if:
          condition:
            lambda: 'return id(current_brightness) == 0;'
          then:
            - homeassistant.service:
                service: light.turn_off
                data:
                  entity_id: !lambda 'return id(selected_entity);'
          else:
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: !lambda 'return id(selected_entity);'
                  brightness: !lambda |-
                    // convert 0..100 -> 0..255 and clamp
                    int val = id(current_brightness);
                    int b = (int)(val * 255.0 / 100.0 + 0.5);
                    if (b < 1) b = 1;   // avoid sending 0
                    if (b > 255) b = 255;
                    return b;

sensor:
  - id: !extend rotary_encoder_id
    name: "Rotary Encoder"
    on_clockwise:
      then:
        - script.execute: screen_bump_activity
        - if:
            condition:
              lambda: 'return id(encoder_button_id).state;'
            then:
              - select.next: dial_selected_light
            else:
              - script.execute: increase_light_brightness

    on_anticlockwise:
      then:
        - script.execute: screen_bump_activity
        - if:
            condition:
              lambda: 'return id(encoder_button_id).state;'
            then:
              - select.previous: dial_selected_light
            else:
              - script.execute: decrease_light_brightness

  # Home Assistant brightness attribute sensors for each selectable light.
  - platform: homeassistant
    id: light_bed_interior_lights_brightness
    entity_id: light.bed_interior_lights
    attribute: brightness
    internal: true
    on_value:
      - script.execute: update_light_display

  - platform: homeassistant
    id: light_main_can_lights_brightness
    entity_id: light.main_can_lights
    attribute: brightness
    internal: true
    on_value:
      - script.execute: update_light_display

  - platform: homeassistant
    id: light_bed_can_lights_brightness
    entity_id: light.bed_can_lights
    attribute: brightness
    internal: true
    on_value:
      - script.execute: update_light_display

  - platform: homeassistant
    id: light_cwww_led_capsule_lights_brightness
    entity_id: light.cwww_led_capsule_lights
    attribute: brightness
    internal: true
    on_value:
      - script.execute: update_light_display

  - platform: homeassistant
    id: light_exterior_lights_brightness
    entity_id: light.exterior_lights
    attribute: brightness
    internal: true
    on_value:
      - script.execute: update_light_display

  - platform: homeassistant
    id: light_door_light_brightness
    entity_id: light.door_light
    attribute: brightness
    internal: true
    on_value:
      - script.execute: update_light_display

  - platform: homeassistant
    id: light_cwww_led_dog_crate_lights_brightness
    entity_id: light.cwww_led_dog_crate_lights
    attribute: brightness
    internal: true
    on_value:
      - script.execute: update_light_display

binary_sensor:
  - id: !extend encoder_button_id
    on_multi_click:
      # Single click
      - timing:
          - ON for at most 500ms
          - OFF for at least 100ms
        then:
          - script.execute: screen_bump_activity
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: !lambda 'return id(selected_entity);'

      # Double click
      - timing:
          - ON for at most 500ms
          - OFF for at most 500ms
          - ON for at most 500ms
          - OFF for at least 100ms
        then:
          - logger.log: "Double click detected - no action assigned"
          - script.execute: screen_bump_activity

      # Long press
      - timing:
          - ON for at least 1000ms
        then:
          - logger.log: "Long press detected - no action assigned"
          - script.execute: screen_bump_activity
