# ============================================================================
# PWM Thermoelectric Cooler (TEC) Dehumidifier Controller
# ============================================================================
# Board: Seeed XIAO ESP32-S3
#

# fan header connector
#   ??
# 12v -> 5v converter mount
# qwiic connector for aht20
# power supply connector
#   Amphenol boardlock connector

# WIRING DIAGRAM
# ==============
#
# XIAO ESP32-S3 Pinout (top view, USB-C at top):
# ┌───────────────────────────────────────────────────────────────────────┐
# │  Left Side              │───[USB-C]─────│              Right Side    │
# │  Pin  │ GPIO  │ Function│               │ Function   │ GPIO  │ Pin   │
# ├───────┼───────┼─────────┤               ├────────────┼───────┼───────┤
# │  D0   │ GPIO1 │ Fan PWM │               │            │  5V   │  5V   │
# │  D1   │ GPIO2 │ Fan Tach│               │            │  GND  │  GND  │
# │  D2   │ GPIO3 │         │               │Sensor power│  3V3  │  3V3  │
# │  D3   │ GPIO4 │ DS18B20 │               │            │ GPIO9 │  D10  │
# │  D4   │ GPIO5 │ I2C SDA │               │  TEC1 PWM  │ GPIO8 │  D9   │
# │  D5   │ GPIO6 │ I2C SCL │               │  TEC2 PWM  │ GPIO7 │  D8   │
# │  D6   │GPIO43 │ (TX)    │               │  (RX)      │GPIO44 │  D7   │
# └───────┴───────┴─────────┴───[ANTENNA]───┴────────────┴───────┴───────┘
#
# Thermoelectric Cooler (TEC) MOSFET WIRING (x2):
# ┌──────────────────────────────────────────────┐
# │  XIAO GPIO ──── MOSFET Gate (via resistor)   │
# │  12V+ ───────── TEC+ (red)                   │
# │  MOSFET Drain ─ TEC- (black)                 │
# │  MOSFET Source ─ GND                         │
# │  (Add flyback diode across TEC terminals)    │
# └──────────────────────────────────────────────┘
#
# FAN PWM WIRING (4-pin PWM fan):
# ┌──────────────────────────────────────────────┐
# │  12V+ ───────── Fan Pin 1 (Yellow/Red)       │
# │  GND ────────── Fan Pin 2 (Black)            │
# │  GPIO2 (D1) ─── Fan Pin 3 (Green) Tach       │
# │  GPIO1 (D0) ─── Fan Pin 4 (Blue) PWM         │
# │                                              │
# │  Tach signal: 2 pulses per revolution        │
# │  (Fan has internal pull-up, no ext resistor) │
# └──────────────────────────────────────────────┘
#
# AHT20 TEMP/HUMIDITY SENSOR (I2C):
# ┌──────────────────────────────────────────────┐
# │  3V3 ────────── VCC                          │
# │  GND ────────── GND                          │
# │  GPIO5 (D4) ─── SDA                          │
# │  GPIO6 (D5) ─── SCL                          │
# └──────────────────────────────────────────────┘
#
# DS18B20 TEMPERATURE SENSORS (One-Wire, 2 sensors):
# ┌──────────────────────────────────────────────┐
# │  3V3 ────────── VCC (red wire)               │
# │  GND ────────── GND (black wire)             │
# │  GPIO4 (D3) ─── DATA (yellow wire)           │
# │  4.7kΩ resistor between DATA and VCC         │
# │                                              │
# │  Cold Side Sensor: Mount on TEC cold plate   │
# │  Hot Side Sensor: Mount on heatsink          │
# └──────────────────────────────────────────────┘
#
# POWER SUPPLY:
# ┌──────────────────────────────────────────────┐
# │  12V DC supply for Thermoelectric Coolers    │
# │  3.3V from XIAO for sensors                  │
# │  Common GND between all components           │
# └──────────────────────────────────────────────┘
#
# ============================================================================

substitutions:
  device_name: pwmdehumidifier
  friendly_name: Dehumidifier
  project_name: Van Dehumidifier
  project_version: "1.0.0"
  log_level: VERBOSE

# added for debugging
web_server:
  port: 80

esphome:
  name: pwmdehumidifier
  friendly_name: ${friendly_name}
  project:
    name: smartvan.${project_name}
    version: ${project_version}

esp32:
  board: seeed_xiao_esp32s3
  framework:
    type: esp-idf

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml

logger:
  logs:
    pulse_counter: WARN
    sensor: INFO
    i2c.idf: WARN

# Globals for deep sleep tracking
globals:
  - id: low_humidity_count
    type: int
    restore_value: no
    initial_value: '0'
  - id: last_tec_power
    type: float
    restore_value: no
    initial_value: '-1.0'

# Deep sleep component
deep_sleep:
  id: deep_sleep_control
  sleep_duration: 5min  # Default, overridden by number entity

output:
  # Thermoelectric Cooler 1 MOSFET PWM
  - platform: ledc
    id: tec1_pwm
    pin: GPIO8   # D9
    frequency: 20000 Hz

  # Thermoelectric Cooler 2 MOSFET PWM
  - platform: ledc
    id: tec2_pwm
    pin: GPIO7   # D8
    frequency: 20000 Hz

  # Fan PWM
  - platform: ledc
    id: fan_pwm
    pin: GPIO1
    frequency: 25000 Hz

  # Shared power level for both Thermoelectric Coolers (and fan)
  - platform: template
    id: tec_power
    type: float
    write_action:
      - lambda: |-
          // state is 0.0 to 1.0 from PID
          float level = state;
          // Clamp to configurable max power
          float max_level = id(tec_max_power).state;
          if (level > max_level) level = max_level;
          
          // Only update if level changed significantly
          if (fabs(level - id(last_tec_power)) < 0.01f) {
            return;  // No significant change, skip update
          }
          id(last_tec_power) = level;
          
          // Drive both Thermoelectric Cooler MOSFETs
          id(tec1_pwm).set_level(level);
          id(tec2_pwm).set_level(level);
          ESP_LOGD("tec_power", "PID requested %.1f%%, clamped to %.1f%% (max %.1f%%)", 
                   state * 100.0f, level * 100.0f, max_level * 100.0f);

i2c:
  sda: GPIO5   # D4
  scl: GPIO6   # D5
  scan: true

one_wire:
  - platform: gpio
    pin: GPIO4   # D3

# https://www.youtube.com/watch?v=9-AZF6udg-Q&t=6s
sensor:
  # Exterior temperature from Home Assistant (for cold weather mode)
  - platform: homeassistant
    name: "Exterior Temperature"
    id: exterior_temp
    entity_id: sensor.outdoor_temperature  # Change to your HA outdoor temp sensor
    unit_of_measurement: "°C"
    filters:
      - filter_out: nan

  # Fan tachometer - 2 pulses per revolution
  - platform: pulse_counter
    pin:
      number: GPIO2   # D1 - Fan tach input
      mode:
        input: true
    name: Fan RPM
    id: fan_rpm
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    filters:
      - multiply: 0.5  # 2 pulses per revolution, counter gives pulses/min
      - delta: 1.0     # Only publish when RPM changes by at least 1
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 1s
    on_value:
      - logger.log:
          format: "Fan RPM changed to %.0f"
          args: ['x']

  - platform: aht10
    variant: AHT20
    temperature:
      name: "Temperature"
      id: box_air_temp
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    humidity:
      name: "Humidity"
      id: box_humidity
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    update_interval: 10s

  - platform: template
    id: dew_point
    name: "Dew Point"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      if (!id(box_air_temp).has_state()) {
        ESP_LOGW("dew_point", "[dew_point] box_air_temp has no state yet");
        return NAN;
      }
      if (!id(box_humidity).has_state()) {
        ESP_LOGW("dew_point", "[dew_point] box_humidity has no state yet");
        return NAN;
      }

      float temperature = id(box_air_temp).state;
      float humidity = id(box_humidity).state;
      
      if (isnan(temperature)) {
        ESP_LOGW("dew_point", "[dew_point] box_air_temp is NaN");
        return NAN;
      }
      if (isnan(humidity)) {
        ESP_LOGW("dew_point", "[dew_point] box_humidity is NaN");
        return NAN;
      }

      // Magnus formula coefficients (valid for -45°C to +60°C)
      const float magnus_coefficient = 17.62;
      const float magnus_temperature_constant = 243.12;  // °C

      float gamma = (magnus_coefficient * temperature) / (magnus_temperature_constant + temperature) + log(humidity / 100.0f);
      float dew = (magnus_temperature_constant * gamma) / (magnus_coefficient - gamma);
      
      ESP_LOGD("dew_point", "Temp: %.1fC, Humidity: %.1f%%, Dew Point: %.1fC", temperature, humidity, dew);
      return dew;

  # Cold side DS18B20 (controls both Thermoelectric Coolers)
  - platform: dallas_temp
    address: 0xd72401000047f728
    name: "Cold Side Temperature"
    id: cold_temp
    update_interval: 5s
    filters:
      - filter_out: nan  # Ignore failed readings
      - exponential_moving_average:
          alpha: 0.2
          send_every: 1
      - delta: 0.1  # Only publish when temp changes by at least 0.1°C

  # Hot side DS18B20 (controls fan + safety)
  - platform: dallas_temp
    address: 0x2222222222222222  # TODO: Replace with actual sensor address from logs
    name: "Hot Side Temperature"
    id: hot_temp
    update_interval: 5s
    filters:
      - filter_out: nan  # Ignore failed readings
      - exponential_moving_average:
          alpha: 0.2
          send_every: 1
      - delta: 0.1  # Only publish when temp changes by at least 0.1°C

binary_sensor:
  - platform: template
    id: hot_overtemp
    name: "Hot Side Overtemp"
    lambda: |-
      if (id(hot_temp).has_state() && id(hot_temp).state > 35.0) {
        return true;
      }
      return false;
    on_press:
      - logger.log: "HOT SIDE OVER TEMP, shutting down both Thermoelectric Coolers"
      - output.turn_off: tec1_pwm
      - output.turn_off: tec2_pwm
      - climate.control:
          id: tec_climate
          mode: "OFF"

climate:
  # https://esphome.io/components/climate/pid/
  - platform: pid
    id: tec_climate
    name: "Dual TEC Cooler"
    sensor: cold_temp
    default_target_temperature: 10 C
    cool_output: tec_power
    visual:
      min_temperature: 0 C
      max_temperature: 30 C
    control_parameters:
      kp: 0.8
      ki: 0.02
      kd: 0.0

number:
  - platform: template
    name: "TEC Max Power"
    id: tec_max_power
    min_value: 0.1
    max_value: 1.0
    step: 0.05
    initial_value: 0.8
    optimistic: true
    restore_value: true
    entity_category: config
    mode: slider
    icon: "mdi:flash-outline"

  - platform: template
    name: "Humidity Target"
    id: humidity_target
    min_value: 30
    max_value: 70
    restore_value: true
    step: 1
    unit_of_measurement: "%"
    initial_value: 60
    optimistic: true
    entity_category: config
    mode: box

  - platform: template
    name: "Dew Point Offset (°C)"
    id: dew_point_offset
    min_value: 0
    max_value: 10
    step: 0.5
    unit_of_measurement: "°C"
    initial_value: 2
    optimistic: true
    restore_value: true
    entity_category: config
    mode: box
    icon: "mdi:thermometer-minus"

  - platform: template
    name: "Wall Insulation Factor"
    id: wall_insulation_factor
    min_value: 0.1
    max_value: 0.9
    step: 0.1
    initial_value: 0.5
    optimistic: true
    restore_value: true
    entity_category: config
    mode: slider
    icon: "mdi:home-thermometer"
    # 0.1 = wall temp close to exterior (poor insulation)
    # 0.9 = wall temp close to interior (good insulation)

# How far below estimated wall temp to keep the dew point when cold outside
  - platform: template
    name: "Cold Weather Safety Margin (°C)"
    id: cold_weather_margin
    min_value: 1
    max_value: 5
    step: 0.5
    unit_of_measurement: "°C"
    initial_value: 2
    optimistic: true
    restore_value: true
    entity_category: config
    mode: box
    icon: "mdi:snowflake-thermometer"

  - platform: template
    name: "Fan Max Temp (°C)"
    id: fan_max_temp
    min_value: 25
    max_value: 70
    step: 1
    unit_of_measurement: "°C"
    initial_value: 35
    optimistic: true
    restore_value: true
    entity_category: config
    mode: box
    icon: "mdi:fan-alert"

  - platform: template
    name: "Sleep Duration (minutes)"
    id: sleep_duration_min
    min_value: 1
    max_value: 30
    step: 1
    unit_of_measurement: "min"
    initial_value: 5
    optimistic: true
    restore_value: true
    entity_category: config
    mode: box
    icon: "mdi:timer-sand"

switch:
  - platform: template
    name: "Deep Sleep Enable"
    id: deep_sleep_enable
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    icon: "mdi:sleep"

  - platform: template
    name: "Prevent Sleep"
    id: prevent_sleep
    optimistic: true
    restore_mode: ALWAYS_OFF
    entity_category: config
    icon: "mdi:sleep-off"
    # Use this to temporarily prevent sleep (e.g., during OTA updates)

fan:
  - platform: speed
    name: "Fan"
    id: fan_speed_control
    output: fan_pwm
    speed_count: 100
    restore_mode: ALWAYS_OFF

interval:
  - interval: 15s
    then:
      - lambda: |-
          float level = 0.0f;
          if (id(hot_temp).has_state() && id(box_air_temp).has_state()) {
            float hot = id(hot_temp).state;
            float ambient = id(box_air_temp).state;
            float max_temp = id(fan_max_temp).state;

            // Fan off when hot side equals ambient, ramps to 100% at max_temp
            // Linear interpolation: 0% at ambient, 100% at max_temp
            if (hot > ambient && ambient < max_temp) {
              level = (hot - ambient) / (max_temp - ambient);
              if (level > 1.0f) level = 1.0f;
              if (level < 0.0f) level = 0.0f;
            }

            // Overtemp forces full fan
            if (id(hot_overtemp).state) {
              level = 1.0f;
              ESP_LOGW("fan", "Overtemp! Forcing fan to 100%%");
            }
            
            ESP_LOGD("fan", "Hot: %.1fC, Ambient: %.1fC, Fan speed: %.0f%%", hot, ambient, level * 100.0f);
          } else {
            ESP_LOGD("fan", "Sensors not ready, fan speed: 0%%");
          }
          id(fan_pwm).set_level(level);

  - interval: 30s
    then:
      - lambda: |-
          if (!id(dew_point).has_state() || !id(box_humidity).has_state()) return;

          float current_humidity = id(box_humidity).state;
          float target_humidity = id(humidity_target).state;
          float interior_temp = id(box_air_temp).state;

          // Cold weather mode: estimate wall temp and adjust target humidity
          float effective_target = target_humidity;
          if (id(exterior_temp).has_state()) {
            float exterior = id(exterior_temp).state;
            float insulation = id(wall_insulation_factor).state;
            float margin = id(cold_weather_margin).state;
            
            // Estimate coldest wall temperature based on insulation factor
            // wall_temp = exterior + (interior - exterior) * insulation_factor
            float wall_temp = exterior + (interior_temp - exterior) * insulation;
            
            // Calculate max humidity where dew point stays below wall temp
            // Using simplified inverse Magnus formula
            float safe_dew_point = wall_temp - margin;
            
            // Calculate max safe humidity for this dew point at current interior temp
            // RH = 100 * exp((17.62 * Td) / (243.12 + Td)) / exp((17.62 * T) / (243.12 + T))
            float gamma_dp = (17.62f * safe_dew_point) / (243.12f + safe_dew_point);
            float gamma_t = (17.62f * interior_temp) / (243.12f + interior_temp);
            float max_safe_humidity = 100.0f * exp(gamma_dp - gamma_t);
            
            // Use the lower of user target or cold-weather safe target
            if (max_safe_humidity < target_humidity) {
              effective_target = max_safe_humidity;
              ESP_LOGI("dehumidifier", "Cold weather mode: Wall temp %.1fC, limiting humidity to %.1f%% (was %.1f%%)", 
                       wall_temp, effective_target, target_humidity);
            }
          }

          // If humidity is below effective target, turn off Thermoelectric Cooler
          if (current_humidity < effective_target) {
            auto call = id(tec_climate).make_call();
            call.set_mode(CLIMATE_MODE_OFF);
            call.perform();
            ESP_LOGD("dehumidifier", "Humidity %.1f%% below target %.1f%%, Thermoelectric Cooler off", current_humidity, effective_target);
            
            // Track consecutive low humidity readings for deep sleep
            id(low_humidity_count) += 1;
            ESP_LOGD("dehumidifier", "Low humidity count: %d", id(low_humidity_count));
            
            // Enter deep sleep after 2 consecutive low humidity checks (1 minute)
            if (id(deep_sleep_enable).state && !id(prevent_sleep).state && id(low_humidity_count) >= 2) {
              int sleep_mins = (int)id(sleep_duration_min).state;
              ESP_LOGI("dehumidifier", "Entering deep sleep for %d minutes", sleep_mins);
              // Set fan PWM high before sleep (high duty = low/off fan speed for 4-pin PWM fans)
              // Then hold the GPIO state during deep sleep
              id(fan_pwm).set_level(1.0f);
              gpio_hold_en(GPIO_NUM_1);  // Hold fan PWM pin (GPIO1) state during deep sleep
              gpio_deep_sleep_hold_en();  // Enable GPIO hold during deep sleep
              id(deep_sleep_control).set_sleep_duration(sleep_mins * 60000);  // Convert to ms
              id(deep_sleep_control).begin_sleep();
            }
            return;
          }
          
          // Reset low humidity counter when dehumidifying
          id(low_humidity_count) = 0;

          // Humidity above target - calculate Thermoelectric Cooler target temp
          float dp = id(dew_point).state;
          if (isnan(dp)) {
            ESP_LOGW("dehumidifier", "Dew point not available, skipping");
            return;
          }
          
          float offset = id(dew_point_offset).state;
          float target = dp - offset;

          // Optional safety clamp so you don't go insanely cold
          if (target < 0.0f) target = 0.0f;

          // Don't enable cooling if hot side is overtemp
          if (id(hot_overtemp).state) {
            ESP_LOGW("dehumidifier", "Hot side overtemp - not enabling Thermoelectric Cooler cooling");
            return;
          }

          ESP_LOGI("dehumidifier", "Dew point: %.1fC, Thermoelectric Cooler target: %.1fC (dew point - %.1fC)", dp, target, offset);

          auto call = id(tec_climate).make_call();
          call.set_mode(CLIMATE_MODE_COOL);
          call.set_target_temperature(target);
          call.perform();
          ESP_LOGD("dehumidifier", "Humidity %.1f%% above target %.1f%%, Thermoelectric Cooler cooling to %.1fC", current_humidity, target_humidity, target);