substitutions:
  device_name: pwmdehumidifier
  friendly_name: Dehumidifier
  project_name: Van Dehumidifier
  project_version: "1.0.0"
  log_level: VERBOSE

esphome:
  name: pwmdehumidifier
  friendly_name: ${friendly_name}
  project:
    name: smartvan.${project_name}
    version: ${project_version}

esp32:
  board: seeed_xiao_esp32s3

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
  
output:
  # TEC1 MOSFET PWM
  - platform: ledc
    id: tec1_pwm
    pin: D1
    frequency: 20000 Hz

  # TEC2 MOSFET PWM
  - platform: ledc
    id: tec2_pwm
    pin: D4
    frequency: 20000 Hz

  # Fan PWM
  - platform: ledc
    id: fan_pwm
    pin: D2
    frequency: 25000 Hz

  # Shared power level for both TECs (and fan)
  - platform: template
    id: tec_power
    type: float
    write_action:
      - lambda: |-
          // state is 0.0 to 1.0 from PID
          float level = state;
          // Drive both TEC MOSFETs
          id(tec1_pwm).set_level(level);
          id(tec2_pwm).set_level(level);

i2c:
  sda: D5
  scl: D6
  scan: true

one_wire:
  - pin: D3

sensor:
  - platform: aht10
    type: AHT20
    temperature:
      name: "Temperature"
      id: box_air_temp
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    humidity:
      name: "Humidity"
      id: box_humidity
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    update_interval: 10s

  - platform: template
    id: dew_point
    name: "Dew Point"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      if (!id(box_air_temp).has_state() || !id(box_humidity).has_state()) {
        return NAN;
      }

      float T = id(box_air_temp).state;
      float RH = id(box_humidity).state;

      const float a = 17.62;
      const float b = 243.12;

      float gamma = (a * T) / (b + T) + log(RH / 100.0f);
      float dew = (b * gamma) / (a - gamma);
      return dew;

  # Cold side DS18B20 (controls both TECs)
  - platform: ds18b20
    # boot and replace with unique one wire address: address: 0x1111111111111111
    name: "Cold Side Temperature"
    id: cold_temp
    update_interval: 2s

  # Hot side DS18B20 (controls fan + safety)
  - platform: ds18b20
    # boot and replace with unique one wire address: address: 0x2222222222222222
    name: "Hot Side Temperature"
    id: hot_temp
    update_interval: 2s

binary_sensor:
  - platform: template
    id: hot_overtemp
    name: "Hot Side Overtemp"
    lambda: |-
      if (id(hot_temp).has_state() && id(hot_temp).state > 70.0) {
        return true;
      }
      return false;
    on_press:
      - logger.log: "HOT SIDE OVER TEMP, shutting down both TECs"
      - output.turn_off: tec1_pwm
      - output.turn_off: tec2_pwm
      - climate.turn_off: tec_climate

climate:
  - platform: pid
    id: tec_climate
    name: "Dual TEC Cooler"
    sensor: cold_temp
    default_target_temperature: 10 C
    cool_output: tec_power
    visual:
      min_temperature: 0 C
      max_temperature: 30 C
    control_parameters:
      kp: 0.8
      ki: 0.02
      kd: 0.0

number:
  - platform: template
    name: "Humidity Target"
    id: humidity_target
    min_value: 30
    max_value: 70
    step: 1
    unit_of_measurement: "%"
    initial_value: 60
    optimistic: true
    entity_category: config
    mode: box

interval:
  - interval: 5s
    then:
      - lambda: |-
          if (!id(hot_temp).has_state()) return;

          float t = id(hot_temp).state;
          float level = 0.0f;

          // Fan curve: 35C to 0.0, 55C to 1.0
          if (t > 35.0f) {
            level = (t - 35.0f) / 20.0f;
            if (level > 1.0f) level = 1.0f;
          }

          // Overtemp forces full fan
          if (id(hot_overtemp).state) {
            level = 1.0f;
          }

          id(fan_pwm).set_level(level);

  - interval: 30s
    then:
      - lambda: |-
          if (!id(dew_point).has_state()) return;

          float dp = id(dew_point).state;
          float target = dp - 2.0f;  // 2C below dew point

          // Optional safety clamp so you don't go insanely cold
          if (target < 0.0f) target = 0.0f;

          auto call = id(tec_climate).make_call();
          call.set_target_temperature(target);
          call.perform();