# ============================================================================
# PWM TEC Dehumidifier Controller
# ============================================================================
# Board: Seeed XIAO ESP32-S3
#

# fan header connector
#   ??
# 1-wire connector, x2
#   ??
# TEC connector, 6A, x2
#   Amphenol boardlock connectors x2
# 12v -> 5v converter mount
# qwiic connector for aht20
# power supply connector
#   Amphenol boardlock connector

# https://github.com/wallnalyr/esp-fan-controller
# ESP32-C3          DS18B20
# ---------         -------
# 3.3V  ──────────── VDD (red)
# GND   ──────────── GND (black)
# GPIO4 ──────┬───── DATA (yellow)
#             │
#            4.7kΩ
#             │
# 3.3V  ──────┘
# 
# ESP32-C3          Noctua Fan
# ---------         ----------
# GPIO8 ──────────── PWM (blue)
# GND   ──────────── GND (black)
#                    +12V (yellow) ── 12V supply
#                    Tach (green) ── (optional, not used)

# WIRING DIAGRAM
# ==============
#
# XIAO ESP32-S3 Pinout:
# ┌─────────────────────────────────────┐
# │  Pin   │ GPIO  │ Function           │
# ├────────┼───────┼────────────────────┤
# │  D0    │ GPIO1 │ Fan PWM            │
# │  D1    │ GPIO2 │ TEC1 MOSFET PWM    │
# │  D2    │ GPIO3 │ Fan Tach (RPM)     │
# │  D3    │ GPIO4 │ DS18B20 One-Wire   │
# │  D4    │ GPIO5 │ TEC2 MOSFET PWM    │
# │  D5    │ GPIO6 │ I2C SDA (AHT20)    │
# │  D6    │ GPIO7 │ I2C SCL (AHT20)    │
# │  3V3   │       │ Sensor power       │
# │  GND   │       │ Common ground      │
# └────────┴───────┴────────────────────┘
# Note: GPIO3 (D2) is a strapping pin - fan tach input only (no external pull)
#
# TEC MOSFET WIRING (x2):
# ┌──────────────────────────────────────────────┐
# │  XIAO GPIO ──── MOSFET Gate (via resistor)   │
# │  12V+ ───────── TEC+ (red)                   │
# │  MOSFET Drain ─ TEC- (black)                 │
# │  MOSFET Source ─ GND                         │
# │  (Add flyback diode across TEC terminals)    │
# └──────────────────────────────────────────────┘
#
# FAN PWM WIRING (4-pin PWM fan):
# ┌──────────────────────────────────────────────┐
# │  12V+ ───────── Fan Pin 1 (Yellow/Red)       │
# │  GND ────────── Fan Pin 2 (Black)            │
# │  GPIO3 (D2) ─── Fan Pin 3 (Green) Tach       │
# │  GPIO1 (D0) ─── Fan Pin 4 (Blue) PWM         │
# │                                              │
# │  Tach signal: 2 pulses per revolution        │
# │  (Fan has internal pull-up, no ext resistor) │
# └──────────────────────────────────────────────┘
#
# AHT20 TEMP/HUMIDITY SENSOR (I2C):
# ┌──────────────────────────────────────────────┐
# │  3V3 ────────── VCC                          │
# │  GND ────────── GND                          │
# │  GPIO6 (D5) ─── SDA                          │
# │  GPIO7 (D6) ─── SCL                          │
# └──────────────────────────────────────────────┘
#
# DS18B20 TEMPERATURE SENSORS (One-Wire, 2 sensors):
# ┌──────────────────────────────────────────────┐
# │  3V3 ────────── VCC (red wire)               │
# │  GND ────────── GND (black wire)             │
# │  GPIO4 (D3) ─── DATA (yellow wire)           │
# │  4.7kΩ resistor between DATA and VCC         │
# │                                              │
# │  Cold Side Sensor: Mount on TEC cold plate   │
# │  Hot Side Sensor: Mount on heatsink          │
# └──────────────────────────────────────────────┘
#
# POWER SUPPLY:
# ┌──────────────────────────────────────────────┐
# │  12V DC supply for TECs and fan              │
# │  3.3V from XIAO for sensors                  │
# │  Common GND between all components           │
# └──────────────────────────────────────────────┘
#
# ============================================================================

substitutions:
  device_name: pwmdehumidifier
  friendly_name: Dehumidifier
  project_name: Van Dehumidifier
  project_version: "1.0.0"
  log_level: VERBOSE

# added for debugging
web_server:
  port: 80

esphome:
  name: pwmdehumidifier
  friendly_name: ${friendly_name}
  project:
    name: smartvan.${project_name}
    version: ${project_version}

esp32:
  board: seeed_xiao_esp32s3
  framework:
    type: esp-idf

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
  
output:
  # TEC1 MOSFET PWM
  - platform: ledc
    id: tec1_pwm
    pin: GPIO2   # D1
    frequency: 20000 Hz

  # TEC2 MOSFET PWM
  - platform: ledc
    id: tec2_pwm
    pin: GPIO5   # D4
    frequency: 20000 Hz

  # Fan PWM
  - platform: ledc
    id: fan_pwm
    pin: GPIO1   # D0 (GPIO3/D2 is a strapping pin)
    frequency: 25000 Hz

  # Shared power level for both TECs (and fan)
  - platform: template
    id: tec_power
    type: float
    write_action:
      - lambda: |-
          // state is 0.0 to 1.0 from PID
          float level = state;
          // Clamp to configurable max power
          float max_level = id(tec_max_power).state;
          if (level > max_level) level = max_level;
          // Drive both TEC MOSFETs
          id(tec1_pwm).set_level(level);
          id(tec2_pwm).set_level(level);

i2c:
  sda: GPIO6   # D5
  scl: GPIO7   # D6
  scan: true

one_wire:
  - platform: gpio
    pin: GPIO4   # D3

# https://www.youtube.com/watch?v=9-AZF6udg-Q&t=6s
sensor:
  # Fan tachometer - 2 pulses per revolution
  - platform: pulse_counter
    pin:
      number: GPIO3   # D2 - Fan tach input
      mode:
        input: true
    name: Fan RPM
    id: fan_rpm
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    filters:
      - multiply: 0.5  # 2 pulses per revolution, counter gives pulses/min
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 1s

  - platform: aht10
    variant: AHT20
    temperature:
      name: "Temperature"
      id: box_air_temp
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    humidity:
      name: "Humidity"
      id: box_humidity
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    update_interval: 10s

  - platform: template
    id: dew_point
    name: "Dew Point"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    lambda: |-
      if (!id(box_air_temp).has_state() || !id(box_humidity).has_state()) {
        return NAN;
      }

      float temperature = id(box_air_temp).state;
      float humidity = id(box_humidity).state;

      // Magnus formula coefficients (valid for -45°C to +60°C)
      const float magnus_coefficient = 17.62;
      const float magnus_temperature_constant = 243.12;  // °C

      float gamma = (magnus_coefficient * temperature) / (magnus_temperature_constant + temperature) + log(humidity / 100.0f);
      float dew = (magnus_temperature_constant * gamma) / (magnus_coefficient - gamma);
      return dew;

  # Cold side DS18B20 (controls both TECs)
  - platform: dallas_temp
    # boot and replace with unique one wire address: address: 0x1111111111111111
    name: "Cold Side Temperature"
    id: cold_temp
    update_interval: 2s

  # Hot side DS18B20 (controls fan + safety)
  - platform: dallas_temp
    # boot and replace with unique one wire address: address: 0x2222222222222222
    name: "Hot Side Temperature"
    id: hot_temp
    update_interval: 2s

binary_sensor:
  - platform: template
    id: hot_overtemp
    name: "Hot Side Overtemp"
    lambda: |-
      if (id(hot_temp).has_state() && id(hot_temp).state > 35.0) {
        return true;
      }
      return false;
    on_press:
      - logger.log: "HOT SIDE OVER TEMP, shutting down both TECs"
      - output.turn_off: tec1_pwm
      - output.turn_off: tec2_pwm
      - climate.control:
          id: tec_climate
          mode: "OFF"

climate:
  - platform: pid
    id: tec_climate
    name: "Dual TEC Cooler"
    sensor: cold_temp
    default_target_temperature: 10 C
    cool_output: tec_power
    visual:
      min_temperature: 0 C
      max_temperature: 30 C
    control_parameters:
      kp: 0.8
      ki: 0.02
      kd: 0.0

number:
  - platform: template
    name: "TEC Max Power"
    id: tec_max_power
    min_value: 0.1
    max_value: 1.0
    step: 0.05
    initial_value: 0.8
    optimistic: true
    restore_value: true
    entity_category: config
    mode: slider
    icon: "mdi:flash-outline"

  - platform: template
    name: "Humidity Target"
    id: humidity_target
    min_value: 30
    max_value: 70
    restore_value: true
    step: 1
    unit_of_measurement: "%"
    initial_value: 60
    optimistic: true
    entity_category: config
    mode: box

interval:
  - interval: 5s
    then:
      - lambda: |-
          if (!id(hot_temp).has_state()) return;

          float temperature = id(hot_temp).state;
          float level = 0.0f;

          // TODO: create a variable which has the low-end fan value, or is this room temperature?

          if (temperature > 35.0f) {
            level = (temperature - 35.0f) / 20.0f;
            if (level > 1.0f) level = 1.0f;
          }

          // Overtemp forces full fan
          if (id(hot_overtemp).state) {
            level = 1.0f;
          }

          id(fan_pwm).set_level(level);

  - interval: 30s
    then:
      - lambda: |-
          if (!id(dew_point).has_state() || !id(box_humidity).has_state()) return;

          float current_humidity = id(box_humidity).state;
          float target_humidity = id(humidity_target).state;

          // If humidity is below target, turn off TEC cooling
          if (current_humidity < target_humidity) {
            auto call = id(tec_climate).make_call();
            call.set_mode(CLIMATE_MODE_OFF);
            call.perform();
            ESP_LOGD("dehumidifier", "Humidity %.1f%% below target %.1f%%, TEC off", current_humidity, target_humidity);
            return;
          }

          // Humidity above target - calculate TEC target temp
          float dp = id(dew_point).state;
          float target = dp - 2.0f;  // 2C below dew point

          // Optional safety clamp so you don't go insanely cold
          if (target < 0.0f) target = 0.0f;

          auto call = id(tec_climate).make_call();
          call.set_mode(CLIMATE_MODE_COOL);
          call.set_target_temperature(target);
          call.perform();
          ESP_LOGD("dehumidifier", "Humidity %.1f%% above target %.1f%%, TEC cooling to %.1fC", current_humidity, target_humidity, target);