# The QuinLED Van Light Controller leverages the QuinLED An-Penta-Deca hardware platform to provide
# interior and exterior lighting in the van. It features 15 individually controllable LED channels,
# controlling various lights such as roof lights, capsule lights, and rear lights.

# Channel       Description
# ------        ----
# 1             Cabin Can Lights (x4)
# 2             Bed Can Lights (x4)
# 3             Sliding Door Light Strip
# 4             Dog Crate Light Strip (warm)
# 5             Dog Crate Light Strip (cold)
# 6             Garage Light Strip
# 7             Capsule Light Strip (Warm)
# 8             Capsule Light Strip (Cool)
# 9             Awning Outside Light Strip
# 10            Awning Inside Light Strip
# 11            Exterior Capsule Driver Flood Light
# 12            Exterior Capsule Passenger Flood Light
# 13            Roof Passenger Flood Lights
# 14            Roof Driver Flood Lights
# 15            Roof Rear Flood Lights

# Cabin Buttons - hooked in through the pcf8574 GPIO expander
# Upper Driver Roof Lights      Turn upper and lower driver roof lights on while pressed
# Lower Driver Capsule Lights   Turn lower driver capsule lights on while pressed
# Rear Roof Lights              Toggle upper rear roof lights on tap, turn on all exterior lights on double tap, turn off all exterior lights on press and hold
# Upper Passenger Roof Lights   Turn upper and lower passenger roof lights on while pressed
# Lower Passenger Roof Lights   Turn lower passenger capsule lights on while pressed

# Garage Pushbutton             Toggle garage lights on press
# Cabin Pushbutton              Toggle cabin can lights on press, turn on interior lights to preset on double tap, turn off all interior lights on press and hold

# todo: Do I have a direct light switch for the rest of the interior lights? Seems like I should have a toggle button somewhere...

# Cabin Dial Controller - connected to home assistant to control brightness of various light groups
# Bed Dial Controller - connected to home assistant to control brightness of various light groups

substitutions:
  device_name: quinled_van_lightcontroller
  friendly_name: QuinLED An-Penta-Deca LED Controller
  project_name: Van Light Controller
  project_version: "1.0.0"

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
      - path: devices/quinled-an-penta-deca.yaml
      - path: i2c/pcf8574.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: smartvan.${project_name}
    version: ${project_version}

light:
  - platform: monochromatic
    id: main_can_lights
    name: "Main Can Lights"
    icon: "mdi:light-recessed"
    default_transition_length: 500ms
    output: led_channel_1

  - platform: monochromatic
    id: bed_can_lights
    name: "Bed Can Lights"
    icon: "mdi:light-recessed"
    default_transition_length: 500ms
    output: led_channel_2

  - platform: monochromatic
    id: door_light
    name: "Door Light"
    default_transition_length: 500ms
    output: led_channel_3

  - platform: cwww
    cold_white: led_channel_4
    warm_white: led_channel_5
    id: cwww_led_dog_crate_lights
    name: "Dog Crate Lights"
    icon: "mdi:led-strip"
    default_transition_length: 500ms
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K

  - platform: monochromatic
    id: garage_led_lights
    name: "Garage Lights"
    default_transition_length: 500ms
    output: led_channel_6

  - platform: cwww
    cold_white: led_channel_7
    warm_white: led_channel_8
    id: cwww_led_capsule_lights
    name: "Bed Capsule Lights"
    icon: "mdi:led-strip"
    default_transition_length: 500ms
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K

  - platform: monochromatic
    id: light_awning_outside_light
    name: "Awning Outside Light Strip"
    icon: "mdi:light-flood-down"
    default_transition_length: 500ms
    output: led_channel_9

  - platform: monochromatic
    id: light_awning_inside_light
    name: "Awning Inside Light Strip"
    icon: "mdi:light-flood-down"
    default_transition_length: 500ms
    output: led_channel_10

  - platform: monochromatic
    id: light_exterior_passenger_capsule
    name: "Exterior Capsule Passenger Flood Light"
    icon: "mdi:light-flood-down"
    default_transition_length: 500ms
    output: led_channel_11

  - platform: monochromatic
    id: light_exterior_driver_capsule
    name: "Exterior Capsule Driver Flood Light"
    icon: "mdi:light-flood-down"
    default_transition_length: 500ms
    output: led_channel_12

  - platform: monochromatic
    id: light_exterior_roof_passenger
    name: "Exterior Roof Passenger Flood Light"
    icon: "mdi:light-flood-down"
    default_transition_length: 500ms
    output: led_channel_13

  - platform: monochromatic
    id: light_exterior_roof_driver
    name: "Exterior Roof Driver Flood Light"
    icon: "mdi:light-flood-down"
    default_transition_length: 500ms
    output: led_channel_14

  - platform: monochromatic
    id: light_exterior_roof_rear
    name: "Exterior Roof Rear Flood Light"
    icon: "mdi:light-flood-down"
    default_transition_length: 500ms
    output: led_channel_15

# Button    Pin         Name                            Action
# ------    ------      -----                           ------
# 1         Button 1    Upper Roof Driver Lights        Turn on the upper and lower roof driver lights as long as the button is on
# 2         Button 2    Upper Roof Passenger Lights     Turn on the upper and lower roof passenger lights
# 3         Button 3    Lower Driver Capsule Lights     Turn on the lower roof driver capsule lights
# 4         Button 4    Lower Passenger Capsule Lights  Turn on the lower roof passenger capsule lights
# 5         Button 5    Rear Roof Lights                tap - Toggle upper rear roof lights
#                                                       double tap - Turn on all exterior lights
#                                                       press and hold - Turn off all exterior lights

# PCF8574 Port Expansion Board which has 8 additional GPIO pins per board.
# This allows us to connect multiple buttons to the QuinLED An-Penta-Deca.

binary_sensor:
  # Button 1 on P0
  - platform: gpio
    name: "${friendly_name} Extended Button 0"
    id: pcf8574_button_0
    pin:
      pcf8574: pcf8574_hub
      number: 0
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - light.turn_on:
          id: light_exterior_roof_rear
          brightness: 100%
    on_release:
      - light.turn_off:
          id: light_exterior_roof_rear


# a button which turns on a light while pressed. This works for the upper/lower passenger/driver roof lights
  - platform: gpio
    name: "${friendly_name} Extended Button 1"
    id: pcf8574_button_1
    pin:
      pcf8574: pcf8574_hub
      number: 1
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_click:
      - if:
          condition:
            light.is_on: light_exterior_roof_rear
          then:
            - light.turn_off: light_exterior_roof_rear
          else:
            - light.turn_on:
                id: light_exterior_roof_rear
                brightness: 100%
    on_release:
      - light.turn_off:
          id: light_exterior_roof_rear
