# https://esphome.io/components/

# The QuinLED Van Light Controller leverages the QuinLED An-Penta-Deca hardware platform to provide
# interior and exterior lighting in the van. It features 15 individually controllable LED channels,
# controlling various lights such as roof lights, capsule lights, and rear lights.

# Channel       Description
# ------        ----
# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
# 9
# 10
# 11
# 12
# 13
# 14
# 15


substitutions:
  device_name: quinled-van-lightcontroller
  friendly_name: QuinLED An-Penta-Deca LED Controller
  pcf_addr: "0x20"        # change if A0/A1/A2 differ

project_version: "1.0.0"
hidden_ssid: true

packages:
  - !include packages/common.yaml
  - !include packages/network/wifi.yaml
  - !include packages/time/homeassistant.yaml
  - !include devices/kincony-kc868-a2v3-sp32-s3.yaml

esphome:
  name: ${device_name}
  friendly name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}

# The QuinLED An-Penta-Deca comes with 6x 6.3A positive terminals. These should be divided evenly.
# The negative side is 15 "medium" power channels at max 5A.


# --- PCF8574 GPIO expander hub ---
pcf8574:
  - id: pcf_buttons
    address: ${pcf_addr}
    i2c_id: bus0



light:
  - platform: cwww
    cold_white: LED_channel_1
    warm_white: LED_channel_2
    id: cwww_led_strip_1
    name: "${device_name}-cct1"
    default_transition_length: 500ms
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K

  - platform: monochromatic
    name: "${device_name}-l3"
    default_transition_length: 1s
    id: LED3
    output: LED_channel_3

  - platform: monochromatic
    name: "${device_name}-l4"
    default_transition_length: 1s
    id: LED4
    output: LED_channel_4
    
  - platform: monochromatic
    name: "${device_name}-l5"
    default_transition_length: 1s
    id: LED5
    output: LED_channel_5

  - platform: monochromatic
    name: "${device_name}-l6"
    default_transition_length: 1s
    id: LED6
    output: LED_channel_6

  - platform: monochromatic
    name: "${device_name}-l7"
    default_transition_length: 1s
    id: LED7
    output: LED_channel_7

  - platform: monochromatic
    name: "${device_name}-l8"
    default_transition_length: 1s
    id: LED8
    output: LED_channel_8

  - platform: monochromatic
    name: "${device_name}-L9"
    default_transition_length: 1s
    id: LED9
    output: LED_channel_9
    
  - platform: monochromatic
    name: "${device_name}-L10"
    default_transition_length: 1s
    id: LED10
    output: LED_channel_10

  - platform: monochromatic
    name: "${device_name}-L11"
    default_transition_length: 1s
    id: LED11
    output: LED_channel_11

  - platform: monochromatic
    name: "${device_name}-L12"
    default_transition_length: 1s
    id: LED12
    output: LED_channel_12

  - platform: monochromatic
    name: "${device_name}-L13"
    default_transition_length: 1s
    id: LED13
    output: LED_channel_13

  - platform: monochromatic
    name: "${device_name}-L14"
    default_transition_length: 1s
    id: LED14
    output: LED_channel_14
    
  - platform: monochromatic
    name: "${device_name}-L15"
    default_transition_length: 1s
    id: LED15
    output: LED_channel_15


# Button    Pin         Name                            Action
# ------    ------      -----                           ------
# 1         Button 1    Upper Roof Driver Lights        Turn on the upper and lower roof driver lights as long as the button is on
# 2         Button 2    Upper Roof Passenger Lights     Turn on the upper and lower roof passenger lights
# 3         Button 3    Lower Driver Capsule Lights     Turn on the lower roof driver capsule lights
# 4         Button 4    Lower Passenger Capsule Lights  Turn on the lower roof passenger capsule lights
# 5         Button 5    Rear Roof Lights                tap - Toggle upper rear roof lights
#                                                       double tap - Turn on all exterior lights
#                                                       press and hold - Turn off all exterior lights


# PCF8574 Port Expansion Board which has 8 additional GPIO pins per board.
# This allows us to connect multiple buttons to the QuinLED An-Penta-Deca.

binary_sensor:

  # Helper for a tidy debounce you can reuse
  - platform: template
    id: _debounce_template
    internal: true

  # Button 1 on P0
  - platform: gpio
    name: "${dev_name} Btn 1"
    id: btn1
    pin:
      pcf8574: pcf_buttons
      number: 0            # P0
      mode:
        input: true
        pullup: true       # expect external pull-up; keeps logic consistent
    inverted: true         # pressed (to GND) ? ON
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_single_click:
      then:
        - homeassistant.event:
            event: esphome.pcf_button
            data: { node: ${dev_name}, button: 1, click: single }
    on_double_click:
      then:
        - homeassistant.event:
            event: esphome.pcf_button
            data: { node: ${dev_name}, button: 1, click: double }


# a button which turns on a light while pressed. This works for the upper/lower passenger/driver roof lights
  - platform: gpio
    pin: 36
    name: Button 1
    id: button_1
    filters:
      - invert:
    on_press:
      - light.turn_on:
            id: cwww_led_strip_1
            brightness: 100%
    on_release:
      - light.turn_off:
                id: cwww_led_strip_1

  - platform: gpio
    pin: 39
    name: Button 2
    id: button_2
    filters:
      - invert:

  - platform: gpio
    pin: 34
    name: Button 3
    id: button_3
    filters:
      - invert:
