# https://esphome.io/components/

# The QuinLED Van Light Controller leverages the QuinLED An-Penta-Deca hardware platform to provide
# interior and exterior lighting in the van. It features 15 individually controllable LED channels,
# controlling various lights such as roof lights, capsule lights, and rear lights.

# Channel       Description
# ------        ----
# 1             Cabin Can Lights (x4)
# 2             Bed Can Lights (x4)
# 3             Sliding Door Light Strip
# 4             Dog Crate Light Strip
# 5             Garage Light Strip
# 6             Capsule Light Strip (Warm)
# 7             Capsule Light Strip (Cool)
# 8             <OPEN>
# 9             Awning Outside Light Strip
# 10            Awning Inside Light Strip
# 11            Exterior Capsule Driver Flood Light
# 12            Exterior Capsule Passenger Flood Light
# 13            Roof Passenger Flood Lights
# 14            Roof Driver Flood Lights
# 15            Roof Rear Flood Lights

# Cabin Buttons - hooked in through the pcf8574 GPIO expander
# Upper Driver Roof Lights      Turn upper and lower driver roof lights on while pressed
# Lower Driver Capsule Lights   Turn lower driver capsule lights on while pressed
# Rear Roof Lights              Toggle upper rear roof lights on tap, turn on all exterior lights on double tap, turn off all exterior lights on press and hold
# Upper Passenger Roof Lights   Turn upper and lower passenger roof lights on while pressed
# Lower Passenger Roof Lights   Turn lower passenger capsule lights on while pressed

# Garage Pushbutton             Toggle garage lights on press
# Cabin Pushbutton              Toggle cabin can lights on press, turn on interior lights to preset on double tap, turn off all interior lights on press and hold

# todo: Do I have a direct light switch for the rest of the interior lights? Seems like I should have a toggle button somewhere...

# Cabin Dial Controller - connected to home assistant to control brightness of various light groups
# Bed Dial Controller - connected to home assistant to control brightness of various light groups

substitutions:
  device_name: quinled-van-lightcontroller
  friendly_name: QuinLED An-Penta-Deca LED Controller

project_version: "1.0.0"
hidden_ssid: true

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
      - path: devices/quinled-an-penta-deca.yaml
      - path: i2c/pcf8574.yaml

esphome:
  name: ${device_name}
  friendly name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}

light:
  - platform: cwww
    cold_white: led_channel_1
    warm_white: led_channel_2
    id: cwww_led_capsule_lights
    name: "Bed Capsule Lights"
    default_transition_length: 500ms
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K

  - platform: monochromatic
    id: bed_can_lights
    name: "Bed Can Lights"
    default_transition_length: 500ms
    output: led_channel_3

  - platform: monochromatic
    id: main_can_lights
    name: "Main Can Lights"
    default_transition_length: 500ms
    output: led_channel_4
    
  - platform: monochromatic
    id: garage_led_lights
    name: "Garage Lights"
    default_transition_length: 500ms
    output: led_channel_5

  - platform: cwww
    cold_white: led_channel_6
    warm_white: led_channel_7
    id: cwww_led_dog_crate_lights
    name: "Dog Crate Lights"
    default_transition_length: 500ms
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K

  - platform: monochromatic
    id: door_light
    name: "Door Light"
    default_transition_length: 500ms
    output: led_channel_8

  - platform: monochromatic
    id: exterior_driver_capsule_light
    name: "Exterior Driver Capsule Light"
    default_transition_length: 500ms
    output: led_channel_9

  - platform: monochromatic
    id: exterior_passenger_capsule_light
    name: "Exterior Passenger Capsule Light"
    default_transition_length: 500ms
    output: led_channel_10

# Button    Pin         Name                            Action
# ------    ------      -----                           ------
# 1         Button 1    Upper Roof Driver Lights        Turn on the upper and lower roof driver lights as long as the button is on
# 2         Button 2    Upper Roof Passenger Lights     Turn on the upper and lower roof passenger lights
# 3         Button 3    Lower Driver Capsule Lights     Turn on the lower roof driver capsule lights
# 4         Button 4    Lower Passenger Capsule Lights  Turn on the lower roof passenger capsule lights
# 5         Button 5    Rear Roof Lights                tap - Toggle upper rear roof lights
#                                                       double tap - Turn on all exterior lights
#                                                       press and hold - Turn off all exterior lights

# PCF8574 Port Expansion Board which has 8 additional GPIO pins per board.
# This allows us to connect multiple buttons to the QuinLED An-Penta-Deca.

binary_sensor:

  # Helper for a tidy debounce you can reuse
  - platform: template
    id: _debounce_template
    internal: true

  # Button 1 on P0
  - platform: gpio
    name: "${dev_name} Btn 1"
    id: btn1
    pin:
      pcf8574: pcf_buttons
      number: 0            # P0
      mode:
        input: true
        pullup: true       # expect external pull-up; keeps logic consistent
    inverted: true         # pressed (to GND) ? ON
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_single_click:
      then:
        - homeassistant.event:
            event: esphome.pcf_button
            data: { node: ${dev_name}, button: 1, click: single }
    on_double_click:
      then:
        - homeassistant.event:
            event: esphome.pcf_button
            data: { node: ${dev_name}, button: 1, click: double }


# a button which turns on a light while pressed. This works for the upper/lower passenger/driver roof lights
  - platform: gpio
    pin: 36
    name: Button 1
    id: button_1
    filters:
      - invert:
    on_press:
      - light.turn_on:
            id: cwww_led_strip_1
            brightness: 100%
    on_release:
      - light.turn_off:
                id: cwww_led_strip_1

  - platform: gpio
    pin: 39
    name: Button 2
    id: button_2
    filters:
      - invert:

  - platform: gpio
    pin: 34
    name: Button 3
    id: button_3
    filters:
      - invert:
