# Recreational Vehicle Programmable Special Module (PSM) Configuration for ESPHome
# using the waveshare esp32 s3 8di 8do board.

# Programmable Special Module Standard Programs
# https://www.mbvans.com/en/upfitter/resources/psm-programs
# https://www.mbvans.com/content/dam/mb-vans/us/upfitter/psm-programs/MY25_RV_Software_Specification_V4.pdf

substitutions:
  device_name: rv-psm-module
  friendly_name: RV PSM Module

project_version: "1.0.0"

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml
      - path: devices/waveshare-esp32-s3-8di-8do.yaml

# https://www.mbvans.com/content/dam/mb-vans/us/upfitter/psm-programs/MY25_RV_Software_Specification_V4.pdf
# outputs:
# hazard warning lights
# vehicle lock

#inputs:
# gear in park

# If your Waveshare board outputs HIGH when triggered (e.g., 12V signal activates optocoupler), and the ESP32 pin sees 3.3V:
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT
    name: "Awning Open Trigger"
    id: awning_open_trigger

# If the signal is active-low (e.g., pulled to GND when triggered):
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
    name: "Awning Open Trigger"
    id: awning_open_trigger


binary_sensor:
  - platform: template
    id: any-door-open
    name: "Any Door Open"
    icon: "mdi:car-door"
    lambda: |-
      if (id(passenger_door_open).state || id(driver_door_open).state || id(sliding_door_open).state || id(rear_door_open).state) {
        return true;
      } else {
        return false;
      }

  - id: !extend di1
    name: "Passenger Door Open"
    comment: "Connector 2, Pin 7, High"
    icon: "mdi:car-door"
    mode: INPUT_PULLDOWN
    on_state:
      - component.update: any-door-open

  - id: !extend di2
    name: "Driver Door Open"
    comment: "Connector 2, Pin 1, High"
    icon: "mdi:car-door"
    mode: INPUT_PULLDOWN
    on_state:
      - component.update: any-door-open

  - id: !extend di3
    name: "Sliding Door Open"
    comment: "Connector 3, Pin 3, Low"
    icon: "mdi:car-door"
    mode: INPUT_PULLUP
    on_state:
      - component.update: any-door-open

  - id: !extend di4
    name: "Rear Door Open"
    comment: "Connector 3, Pin 13, Low"
    icon: "mdi:car-door"
    mode: INPUT_PULLUP
    on_state:
      - component.update: any-door-open


  - id: !extend di5
    name: "Vehicle Locked"
    comment: "Connector 3, Pin 31, High"
    icon: "mdi:car-lock"
    mode: INPUT_PULLDOWN

  - id: !extend di6
    name: "Vehicle Unlocked"
    comment: "Connector 3, Pin 32, High"
    icon: "mdi:car-lock"
    mode: INPUT_PULLDOWN


  # - id: !extend di7
  #   name: "Gear in 'P'"
  #   comment: "Connector 2, Pin 6, High"
  #   icon: "mdi:car-shift-pattern"

  # - id: !extend di8
  #   name: "Gear in 'R'"
  #   comment: "Connector 2, Pin 9, High"
  #   icon: "mdi:car-shift-pattern"

  # - id: !extend di1
  #   name: "Gear NOT in 'P'"
  #   comment: "Connector 2, Pin 22, High"
  #   icon: "mdi:car-shift-pattern"

  - id: !extend di1
    name: "Vehicle Speed > 0 mph"
    comment: "Connector 3, Pin 21, High"
    icon: "mdi:speedometer"
    mode: INPUT_PULLDOWN

    # Ignition On
    # Park Brake ON

    # Brake Lights
    # Left Turn Signal
    # Right Turn Signal


switch:
  - id: !extend do1
    name: "Vehicle Lock"
    comment: "Connector 3, Pin 30"
    icon: "mdi:car-lock"
    device_class: lock

  - id: !extend do2
    name: "Hazard Warning Lights"
    comment: "Connector 3, Pin 23"
    icon: "mdi:car-hazard"
    device_class: safety

  - id: !extend do3
    disabled_by_default: true
  - id: !extend do4
    disabled_by_default: true
  - id: !extend do5
    disabled_by_default: true
  - id: !extend do6
    disabled_by_default: true
  - id: !extend do7
    disabled_by_default: true
  - id: !extend do8
    disabled_by_default: true
