# The Van Awning and Solar cover controller uses a BEVRLink 4 Relay + 4 Button
# controller to control the cover states for two awnings.

# TODO: hook up in/out switches for awning controller to GPIO pins.

substitutions:
  device_name: van_cover_relay_controller
  friendly_name: Cover Controller
  project_name: Van Cover Controller
  project_version: "1.0.0"
  log_level: DEBUG

esphome:
  name: van_cover_relay_controller
  friendly_name: ${friendly_name}
  project:
    name: smartvan.${project_name}
    version: ${project_version}
  on_boot:
    priority: -100  # Run after all components are initialized
    then:
      - logger.log: "Boot: Closing awnings"
      - cover.close: nomadic_awning_cover
      - cover.close: solar_panel_cover

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml

      - path: i2c/ina260.yaml
        vars:
          i2c_bus_id: i2c_bus
          i2c_address: 0x40
          ina260_sensor_id: nomadic_awning_cover_motor_current
          ina260_current_sensor_id: nomadic_motor_current_sensor
          ina260_current_sensor_name: "Nomadic Awning Motor Current Sensor"

      - path: i2c/ina260.yaml
        vars:
          i2c_bus_id: i2c_bus
          i2c_address: 0x41
          ina260_sensor_id: solar_panel_cover_motor_current
          ina260_current_sensor_id: solar_panel_motor_current_sensor
          ina260_current_sensor_name: "Solar Panel Motor Current Sensor"

      - path: devices/bevrlink-4ch-esp32-relay.yaml

      - path: packages/relay-current-cover-controller.yaml
        vars:
          cover_name: Nomadic Awning
          cover_id: nomadic_awning_cover
          current_sensor_id: nomadic_motor_current_sensor
          current_sensor_parent_id: nomadic_awning_cover_motor_current
          relay_1_id: relay1
          relay_2_id: relay2

      - path: packages/relay-current-cover-controller.yaml
        vars:
          cover_name: Solar Panel
          cover_id: solar_panel_cover
          current_sensor_id: solar_panel_motor_current_sensor
          current_sensor_parent_id: solar_panel_cover_motor_current
          relay_1_id: relay3
          relay_2_id: relay4

switch:
  - id: !extend relay1
    internal: true
  - id: !extend relay2
    internal: true
  - id: !extend relay3
    internal: true
  - id: !extend relay4
    internal: true

sensor:
  - platform: homeassistant
    name: "Sun Elevation"
    id: sun_elevation
    entity_id: sun.sun
    attribute: elevation
    unit_of_measurement: "°"
    accuracy_decimals: 2
    internal: true
    on_value:
      then:
        - script.execute: adjust_solar_awning_based_on_sun

# GPIO buttons to control the awning covers.
binary_sensor:
  - platform: gpio
    name: Open Nomadic Awning Button
    id: button1
    pin:
      number: 4
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
       then:
         - cover.open: nomadic_awning_cover

  - platform: gpio
    name: Close Nomadic Awning Button
    id: button2
    pin:
      number: 5
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
       then:
         - cover.close: nomadic_awning_cover

script:
  # Automatically close the solar awning when the sun sets.
  - id: adjust_solar_awning_based_on_sun
    then:
      - if:
          condition:
            lambda: 'return id(sun_elevation).state < 0.0;'
          then:
            - logger.log: "Sun is low - retracting solar awning"
            - cover.close: solar_panel_cover

