# https://docs.m5stack.com/en/homeassistant/kit/tab5_ha_hmi

substitutions:
  device_name: van_tablet
  friendly_name: Van Tablet Controller
  project_name: Van Tab5 Tablet Controller
  project_version: "1.0.0"
  log_level: DEBUG

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "M5Stack Tab5 Van Tablet Controller"
  project:
    name: smartvan.${project_name}
    version: ${project_version}

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/icons/network_icons.yaml
      - path: packages/icons/battery_icons.yaml
      - path: packages/icons/weather_icons.yaml
      - path: packages/icons/homeassistant_icons.yaml
      - path: devices/M5Stack-Tab5.yaml

wifi:
  on_connect:
    - lvgl.label.update:
        id: lbl_wifi_status
        text: "\U000F0928"  # wifi-strength-4 as default when connected
  on_disconnect:
    - lvgl.label.update:
        id: lbl_wifi_status
        text: "\U000F05AA"  # wifi-off

api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_connection_status
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_connection_status

time:
  - id: !extend rtc_time
    on_time:
      # Update once ready
      - seconds: /3
        then:
          - lvgl.label.update:
              id: lbl_time
              text: !lambda |-
                auto t = id(ha_time).now();
                return t.strftime("%H:%M").c_str();

          - lvgl.label.update:
              id: lbl_date
              text: !lambda |-
                auto t = id(ha_time).now();
                return t.strftime("%Y-%m-%d %a").c_str();

lvgl:
  bg_color: 0x00FF00
  on_idle:
    timeout: 30s
    then:
      - logger.log: "LVGL is idle"
      - light.turn_off: backlight
      - lvgl.pause:

  on_boot:
    then:
      - logger.log: "LVGL boot"

  on_ready:
    then:
      - logger.log: "LVGL ready - updating display"

  on_resume:
    then:
      - logger.log: "LVGL resume"

  touchscreens:
    - touchscreen_id: touchscreen_id
      long_press_time: 400ms
      long_press_repeat_time: 100ms

  top_layer:
    bg_color: 0x00FF00
    widgets:
      - obj:
          id: header_container
          width: 100%
          height: 40
          align: TOP_LEFT
          bg_color: 0x000000
          border_width: 0
          pad_all: 5
          layout:
            type: flex
            flex_flow: row

          widgets:
            - label:
                id: lbl_time
            - label:
                id: lbl_date

            - label:
                id: lbl_connection_status
                text_font: homeassistant_icons
                text: "\U000F07D0"
                text_color: 0x03A9F4 # Blue color for Home Assistant icon

            - label:
                id: lbl_wifi_status
                text: "\U000F05AA"  # wifi-off icon by default
                text_font: wifi_icons
                text_color: 0x888888  # Gray for disconnected

            - label:
                id: lbl_battery_power_cord
                text: "\U000F1C3B"
                text_font: battery_icons
                text_color: 0xFFFFFF
                hidden: true  # Initially hidden

            - label:
                id: lbl_battery_status
                align: TOP_LEFT
                text: "\U000F0091"
                text_font: battery_icons
                text_color: 0xFFFFFF      