# The Van Awning and Solar cover controller uses a BEVRLink 4 Relay + 4 Button
# controller to control the cover states for two awnings.
esphome:
  name: van-cover-relay-controller
  friendly_name: "Van Cover Controller"
  on_boot:
    then:
       # Indicate that the covers are both closed by default?

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

packages:
  remote_packages:
    url: https://github.com/rluengen/esphome
    ref: main
    refresh: always
    files:
      - path: packages/common.yaml
        vars:
          api_encryption_key: !secret encryption_key
      - path: packages/network/wifi.yaml
        vars:
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password
      - path: packages/time/homeassistant.yaml

      - path: i2c/ina260.yaml
        vars:
          i2c_bus_id: i2c_bus
          i2c_address: 0x40
          ina260_sensor_id: nomadic_awning_cover_motor_current
          ina260_current_sensor_id: nomadic_motor_current_sensor
          ina260_current_sensor_name: "Nomadic Awning Motor Current Sensor"

      - path: i2c/ina260.yaml
        vars:
          i2c_bus_id: i2c_bus
          i2c_address: 0x41
          ina260_sensor_id: solar_panel_cover_motor_current
          ina260_current_sensor_id: solar_panel_motor_current_sensor
          ina260_current_sensor_name: "Solar Panel Motor Current Sensor"

      - path: packages/relay-current-cover-controller.yaml
        vars:
          cover_name: Nomadic Awning
          cover_id: nomadic_awning_cover
          current_sensor_id: nomadic_motor_current_sensor
          relay_1_id: relay1
          relay_2_id: relay2

      - path: packages/relay-current-cover-controller.yaml
        vars:
          cover_name: Solar Panel
          cover_id: solar_panel_cover
          current_sensor_id: solar_panel_motor_current_sensor
          relay_1_id: relay3
          relay_2_id: relay4

      - path: devices/bevrlink-4ch-esp32-relay.yaml
        vars:
          button_1_name: "Open Nomadic Awning"
          button_1_press_action: open_nomadic_awning_script
          button_2_name: "Close Nomadic Awning Button"
          button_2_press_action: close_nomadic_awning_script
          button_3_name: "Open Solar Panel"
          button_3_press_action: open_solar_awning_script
          button_4_name: "Close Solar Panel Button"
          button_4_press_action: close_solar_awning_script

script:
  - id: update_nomadic_motor_current_while_moving
    then:
      - logger.log: "Starting current updates while nomadic awning moving"
      - while:
          condition:
            - lambda: 'return id(nomadic_awning_cover).state == COVER_OPENING || id(nomadic_awning_cover).state == COVER_CLOSING;'
          then:
            - sensor.update: nomadic_awning_cover_motor_current
            - delay: 250ms
      - logger.log: "Nomadic awning stopped moving; update loop finished"

  - id: update_solar_motor_current_while_moving
    then:
      - logger.log: "Starting current updates while solar panel moving"
      - while:
          condition:
            - lambda: 'return id(solar_panel_cover).state == COVER_OPENING || id(solar_panel_cover).state == COVER_CLOSING;'
          then:
            - sensor.update: solar_panel_cover_motor_current
            - delay: 250s
      - logger.log: "Solar panel stopped moving; update loop finished"

  - id: open_nomadic_awning_script
    then:
      - cover.open: nomadic_awning_cover
      - script.execute: update_nomadic_motor_current_while_moving

  - id: close_nomadic_awning_script
    then:
      - cover.close: nomadic_awning_cover
      - script.execute: update_nomadic_motor_current_while_moving

  - id: open_solar_awning_script
    then:
      - cover.open: solar_panel_cover
      - script.execute: update_solar_motor_current_while_moving

  - id: close_solar_awning_script
    then:
      - cover.close: solar_panel_cover
      - script.execute: update_solar_motor_current_while_moving
