# ESPHome config for Waveshare 8.8-DSI-TOUCH-A on ESP32-P4
# Uses MIPI-DSI display with LVGL and a centered "hello world" label

substitutions:
  device_name: wavesharedsi
  friendly_name: Waveshare 8.8" DSI
  log_level: VERBOSE

# Local external component for DSI display init with BSP-correct order
# Required because built-in mipi_dsi sends DCS after panel_init (blank screen).
# OTA7290B bridge needs DCS SLPOUT/DISPON BEFORE DPI video starts.
external_components:
  - source:
      type: local
      path: components
    components: [waveshare_dsi]

# added for debugging
# web_server:  # Disabled - requires WiFi
#   port: 80

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  on_boot:
    - priority: 600
      then:
        - lambda: |-
            // === Waveshare OTA7290B Bridge Init (BSP-matched order) ===
            // BSP: HW Reset -> MCU Init -> 1s delay -> DSI bus -> DCS -> DPI
            // We match this by doing HW reset + MCU init with a BLOCKING
            // 1s delay here, before the display component runs at priority ~250.

            // Step 1: Hardware reset via GPIO27 (BSP_LCD_DSI_RST)
            gpio_set_direction(GPIO_NUM_27, GPIO_MODE_OUTPUT);
            gpio_set_level(GPIO_NUM_27, 1);
            delay(10);
            gpio_set_level(GPIO_NUM_27, 0);
            delay(10);
            gpio_set_level(GPIO_NUM_27, 1);
            delay(50);

            // Step 2: MCU init (register 0x95) per Waveshare OTA7290B driver
            id(display_backlight_i2c).write_byte(0x95, 0x11);
            delay(10);
            id(display_backlight_i2c).write_byte(0x95, 0x17);

            // Step 3: Backlight on (direct I2C)
            id(display_backlight_i2c).write_byte(0x96, 0xFF);

            // Step 4: Wait 1000ms for bridge to stabilize (BLOCKING)
            delay(1000);
            ESP_LOGI("waveshare", "OTA7290B bridge init complete");
    - priority: 200
      then:
        - light.turn_on:
            id: display_backlight
            brightness: 100%

# ESP32-C6 co-processor for WiFi via SDIO
# See: https://esphome.github.io/esp-hosted-firmware/
esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

# Embedded co-processor firmware update (no WiFi/HTTP needed)
update:
  - platform: esp32_hosted
    name: "ESP32-C6 Firmware"
    type: embedded
    path: network_adapter_esp32c6.bin
    sha256: 2aa46dbcd18f5b2046f58b82cdc62bdf21af137930e67c4b3b114f6e3e0daf15

# packages:
#   remote_packages:
#     url: https://github.com/rluengen/esphome
#     ref: main
#     refresh: always
#     files:
#       - path: packages/common.yaml
#         vars:
#           api_encryption_key: !secret encryption_key
#       - path: packages/network/wifi.yaml
#         vars:
#           wifi_ssid: !secret wifi_ssid
#           wifi_password: !secret wifi_password

# Ethernet - DISABLED (Waveshare 8.8" DSI may not have IP101 PHY)
# ethernet:
#   type: IP101
#   mdc_pin: GPIO31
#   mdio_pin: GPIO52
#   power_pin: GPIO51
#   clk:
#     mode: CLK_EXT_IN
#     pin: GPIO50
#   phy_addr: 1

esp32:
  board: esp32-p4-evboard
  variant: esp32p4
  flash_size: 16MB
  framework:
    type: esp-idf

# Required for MIPI-DSI display
psram:
  mode: hex
  speed: 200MHZ

# LDO for MIPI-DSI PHY - required for display to initialize
esp_ldo:
  - voltage: 2.5V
    channel: 3

logger:
  level: VERBOSE
  hardware_uart: UART0

# I2C for GT911 Touchscreen and panel/backlight MCU
# ESP32-P4 EVBoard default I2C used here
i2c:
  sda: GPIO7
  scl: GPIO8
  frequency: 400kHz
  scan: false

# I2C device for panel/backlight control (address 0x45)
i2c_device:
  - address: 0x45
    id: display_backlight_i2c

# Backlight brightness control as a light
output:
  - platform: template
    id: backlight_output
    type: float
    write_action:
      - lambda: |-
          // Write brightness to register 0x96 (0x00=off, 0xFF=full)
          // Per Waveshare wiki: ESP32-P4 uses register 0x96 at I2C address 0x45
          uint8_t brightness = (uint8_t)(state * 255);
          id(display_backlight_i2c).write_byte(0x96, brightness);

light:
  - platform: monochromatic
    name: "Display Backlight"
    id: display_backlight
    output: backlight_output
    default_transition_length: 250ms
    restore_mode: ALWAYS_ON

# MIPI-DSI Display - Waveshare 8.8" (480x1920 portrait)
# Using waveshare_dsi external component because built-in mipi_dsi sends DCS
# commands AFTER panel_init (starts DPI video), but OTA7290B bridge needs
# DCS SLPOUT/DISPON in LP mode BEFORE DPI video starts.
waveshare_dsi:
  id: dsi_display

# Built-in mipi_dsi DISABLED - ordering incompatible with OTA7290B bridge
# display:
#   - platform: mipi_dsi
#     id: dsi_display
#     model: CUSTOM
#     rotation: 0
#     dimensions:
#       width: 480
#       height: 1920
#     lanes: 2
#     color_order: rgb
#     hsync_front_porch: 50
#     hsync_pulse_width: 50
#     hsync_back_porch: 50
#     vsync_front_porch: 20
#     vsync_pulse_width: 20
#     vsync_back_porch: 20
#     pclk_frequency: 75000000
#     lane_bit_rate: 1300Mbps
#     color_depth: 16
#     pixel_mode: 16bit
#     init_sequence:
#       - [0x11, 0x00]  # Sleep Out (with param byte for DCS 0x15 packet)
#       - delay 120ms
#       - [0x29, 0x00]  # Display On (with param byte for DCS 0x15 packet)
#       - delay 20ms

# Periodic diagnostics: confirm backlight writes and read MCU status
interval:
  - interval: 20s
    then:
      - lambda: |-
          float b = id(display_backlight).current_values.get_brightness();
          uint8_t brightness = (uint8_t)(b * 255);
          bool ack_96 = id(display_backlight_i2c).write_byte(0x96, brightness);
          uint8_t status = 0;
          id(display_backlight_i2c).read_byte(0x80, &status);
          ESP_LOGI("panel_diag", "Backlight 0x96=%d ACK: %s, MCU status 0x80: 0x%02X", brightness, ack_96 ? "YES" : "NO", status);

# GT911 Touchscreen
touchscreen:
  - platform: gt911
    id: dsi_touchscreen
    update_interval: 200ms

# LVGL with centered "hello world" label
lvgl:
  displays:
    - dsi_display
  touchscreens:
    - dsi_touchscreen
  color_depth: 16
  buffer_size: 100%
  byte_order: little_endian
  pages:
    - id: main_page
      bg_color: 0x0000FF
      widgets:
        - label:
            text: "hello world"
            align: CENTER
            text_font: montserrat_48
            text_color: 0xFFFFFF
