# Base WiFi Configuration
# Include this in your device configs with: <<: !include templates/base/wifi.yaml

wifi:
  # fast_connect: Skips WiFi channel scanning, connects directly to last known BSSID/channel
  # Benefits: Faster boot time (~3-5s savings), lower power consumption during connection
  # Drawbacks: Won't roam between APs in mesh networks, breaks if router changes channel
  # Recommendation: Enable for stationary devices with single AP, disable for mobile/multi-AP setups
  fast_connect: true
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  min_auth_mode: WPA2
  on_connect: 
    then:
    - logger.log: "Connected to WiFi"
  on_disconnect:
    then:
    - logger.log: "Disconnected from WiFi"

# Text sensor for device information
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "WiFi IP Address"
      entity_category: diagnostic
      filters:
        - lambda: |-
            static std::string last;
            if (last != x) {
              last = x;
              return x;
            } else {
              return {};
            }
    ssid:
      name: "SSID"
      entity_category: diagnostic
    bssid:
      name: "BSSID"
      entity_category: diagnostic

sensor:
  - platform: wifi_signal
    id: wifi_rssi
    name: "WiFi Signal"
    update_interval: 60s
    filters:
      - throttle: 5min
    on_value:
      then:
        - lambda: |-
            static int last_bars = -1;
            int bars = 0;
            if (!isnan(id(wifi_rssi).state)) {
              float r = id(wifi_rssi).state;
              if      (r > -55) bars = 4;
              else if (r > -65) bars = 3;
              else if (r > -72) bars = 2;
              else if (r > -80) bars = 1;
              else               bars = 0;
            }

            if (bars != last_bars) {
              last_bars = bars;
              // TODO: the wifi bar count has changed: id(redraw_debounced).execute();
            }
