# Dallas DS18B20 Temperature Sensor Template
# One-wire temperature sensor, supports multiple sensors on one pin

dallas:
  - pin: GPIO23  # Change this to your GPIO pin
    update_interval: 60s

sensor:
  - platform: dallas
    address: 0x1234567890abcdef  # Replace with your sensor address (found in logs)
    name: "${friendly_name} Temperature"
    accuracy_decimals: 2
    resolution: 12  # Options: 9, 10, 11, 12 (higher = more accurate but slower)

# For multiple sensors, duplicate the sensor block with different addresses:
#  - platform: dallas
#    address: 0xabcdef1234567890
#    name: "${friendly_name} Temperature 2"
