# Relay with Physical Button Template
# Combines relay control with a physical button/switch

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0  # Change to your button GPIO
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay_1

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO12  # Change to your relay GPIO
    id: relay_1
    restore_mode: RESTORE_DEFAULT_OFF
