

external_components:
  - source: github://dala318/esphome-qmi8658

sensor:
  - platform: qmi8658
    address: 0x6B              # Use 0x6A if SA0 is low
    # interrupt_pin_1: GPIO10   # You can try this, but IRQ2 is recommended
    interrupt_pin_2: GPIO13

    # Optional tuning (examples shown by the component author)
    acceleration_range: 4G
    acceleration_odr: 100hz
    acceleration_lpf_mode: "0"
    gyroscope_range: "64DPS"
    gyroscope_odr: "896.8HZ"
    gyroscope_lpf_mode: "3"

    # Exposed sensors
    acceleration_x:
      name: "Accelerometer X"
    acceleration_y:
      name: "Accelerometer Y"
    acceleration_z:
      name: "Accelerometer Z"
    gyroscope_x:
      name: "Gyroscope X"
    gyroscope_y:
      name: "Gyroscope Y"
    gyroscope_z:
      name: "Gyroscope Z"
    temperature:
      name: "Temperature"
    update_interval: 5s
