substitutions:
  button_1_name: "Button 1"
  button_1_press_action: ""
  button_1_release_action: ""
  button_2_name: "Button 2"
  button_2_press_action: ""
  button_2_release_action: ""
  button_3_name: "Button 3"
  button_3_press_action: ""
  button_3_release_action: ""
  button_4_name: "Button 4"
  button_4_press_action: ""
  button_4_release_action: ""

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

binary_sensor:
  - platform: gpio
    name: ${button_1_name}
    id: button1
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
    on_press:
      then:
        - ${button_1_press_action}
    on_release:
      then:
        - ${button_1_release_action}

  - platform: gpio
    name: ${button_2_name}
    id: button2
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
    on_press:
      then:
        - ${button_2_press_action}
    on_release:
      then:
        - ${button_2_release_action}

  - platform: gpio
    name: ${button_3_name}
    id: button3
    pin:
      number: GPIO20
      mode: INPUT_PULLUP
    on_press:
      then:
        - ${button_3_press_action}
    on_release:
      then:
        - ${button_3_release_action}

  - platform: gpio
    name: ${button_4_name}
    id: button4
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
    on_press:
      then:
        - ${button_4_press_action}
    on_release:
      then:
        - ${button_4_release_action}
  
switch:
  - platform: gpio
    name: "Relay 1"
    id: relay1
    pin: GPIO10

  - platform: gpio
    name: "Relay 2"
    id: relay2
    pin: GPIO11

  - platform: gpio
    name: "Relay 3"
    id: relay3
    pin: GPIO22

  - platform: gpio
    name: "Relay 4"
    id: relay4
    pin: GPIO23