# The QuinLED An-Penta-Deca comes with 6x 6.3A positive terminals. These should be divided evenly.
# The negative side is 15 "medium" power channels at max 5A.

# https://quinled.info/quinled-an-penta-deca-esphome-configuration-example/

esp32:
  board: esp32dev
  framework:
    type: esp-idf

i2c:
  id: i2c_bus
  sda:
    number: 15
    ignore_strapping_warning: true
  scl: 16
  scan: true

output:
  - platform: ledc
    pin: 27
    frequency: 19531Hz
    id: led_channel_1

  - platform: ledc
    pin: 26
    frequency: 19531Hz
    id: led_channel_2

  - platform: ledc
    pin: 25
    frequency: 19531Hz
    id: led_channel_3

  - platform: ledc
    pin: 23
    frequency: 19531Hz
    id: led_channel_4

  - platform: ledc
    pin: 22
    frequency: 19531Hz
    id: led_channel_5

  - platform: ledc
    pin: 21
    frequency: 19531Hz
    id: led_channel_6

  - platform: ledc
    pin: 19
    frequency: 19531Hz
    id: led_channel_7

  - platform: ledc
    pin: 18
    frequency: 19531Hz
    id: led_channel_8

  - platform: ledc
    pin: 17
    frequency: 19531Hz
    id: led_channel_9

  - platform: ledc
    pin: 14
    frequency: 19531Hz
    id: led_channel_10

  - platform: ledc
    pin: 13
    frequency: 19531Hz
    id: led_channel_11

  - platform: ledc
    pin:
      number: 12
      ignore_strapping_warning: true
    frequency: 19531Hz
    id: led_channel_12

  - platform: ledc
    pin:
      number: 5
      ignore_strapping_warning: true
    frequency: 19531Hz
    id: led_channel_13

  - platform: ledc
    pin: 4
    frequency: 19531Hz
    id: led_channel_14

  - platform: ledc
    pin:
      number: 2
      ignore_strapping_warning: true
    frequency: 19531Hz
    id: led_channel_15

binary_sensor:
  - platform: gpio
    id: button_1
    pin: 36
    filters:
      - invert:

  - platform: gpio
    id: button_2
    pin: 39
    filters:
      - invert:

  - platform: gpio
    id: button_3
    pin: 34
    filters:
      - invert:

  - platform: gpio
    id: button_4
    pin: 33
    filters:
      - invert:
