# 2.8" Round Display Development Board, 480x480
#
# Hardware configuration file
# https://github.com/agillis/esphome-modular-lvgl-buttons/blob/main/hardware/waveshare-esp32-s3-touch-lcd-2.8c.yaml
# https://community.home-assistant.io/t/waveshare-esp32-s3-touch-lcd-2-8c-working-config/836834

substitutions:
  touchscreen_id: touch_id
  display_id: touch_lcd_display_id
  display_backlight_id: display_backlight_id

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHFREQ: "80MHz" # this is needed for flashing
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_FLASHMODE_QIO: y
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ: '240'
      CONFIG_SPIRAM_RODATA: "y"

psram:
  mode: octal
  speed: 80MHz

preferences:
  flash_write_interval: 5min

# PCA9554 GPIO extender
pca9554:
  - id: p_c_a
    address: 0x20
    i2c_id: i2c_bus

# Backlight PWM output and light component
output:
    # Backlight LED
  - platform: ledc
    id: gpio_backlight_pwm
    pin: GPIO06
    frequency: 2000Hz
    channel: 0

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: ${display_backlight_id}
    restore_mode: ALWAYS_ON
    gamma_correct: 1

#-------------------------------------------
# Touchscreen GT911 i2c
#-------------------------------------------
i2c:
  - id: i2c_bus
    sda: 15
    scl: 7
    scan: true

# GT911 Touchscreen Controller
touchscreen:
  - platform: gt911
    id: ${touchscreen_id}
    i2c_id: i2c_bus
    reset_pin:
      pca9554: p_c_a
      number: 1
    interrupt_pin: GPIO16
    # on_update:
        # - lvgl.label.update:
            # id: coord_text
            # text: !lambda return str_sprintf("Touch points:\n id=%d x=%d, y=%d", touches[0].id, touches[0].x, touches[0].y);
        # - lambda: |-
            # for (auto touch: touches)  {
                # if (touch.state <= 2) {
                  # ESP_LOGI("Touch points:", "id=%d x=%d, y=%d", touch.id, touch.x, touch.y);
                # }
            # }

#-------------------------------------------
# Display ST7701S spi
#-------------------------------------------
spi:
  - id: spi_lcd
    clk_pin: GPIO02
    mosi_pin: GPIO01
    interface: spi3

display:
  - platform: st7701s
    id: ${display_id}
    spi_id: spi_lcd
    spi_mode: MODE0
    color_order: bgr
    auto_clear_enabled: false
    # show_test_card: true
    dimensions:
      width: 480
      height: 480
    cs_pin:
      pca9554: p_c_a
      number: 2
    reset_pin:
      pca9554: p_c_a
      number: 0
    de_pin: GPIO40
    hsync_pin: GPIO38
    vsync_pin: GPIO39
    pclk_pin: GPIO41
    # RGB timing from official Waveshare/wireless-tag ZX2D10GE01R-V4848 demo
    # https://github.com/wireless-tag-com/ZX2D10GE01R-V4848/blob/ad21b365/main/screen.c
    pclk_frequency: 15MHz
    pclk_inverted: false
    hsync_pulse_width: 10
    hsync_back_porch: 10
    hsync_front_porch: 10
    vsync_pulse_width: 2
    vsync_back_porch: 12
    vsync_front_porch: 14
    # Init sequence from official Waveshare/wireless-tag ZX2D10GE01R-V4848 demo
    init_sequence:
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x13 ]
      - [ 0xEF, 0x08 ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x10 ]
      - [ 0xC0, 0x3B, 0x00 ]
      - [ 0xC1, 0x0B, 0x02 ]
      - [ 0xC2, 0x07, 0x02 ]
      - [ 0xCC, 0x10 ]
      - [ 0xCD, 0x08 ]
      - [ 0xB0, 0x00, 0x11, 0x16, 0x0E, 0x11, 0x06, 0x05, 0x09, 0x08, 0x21, 0x06, 0x13, 0x10, 0x29, 0x31, 0x18 ]
      - [ 0xB1, 0x00, 0x11, 0x16, 0x0E, 0x11, 0x07, 0x05, 0x09, 0x09, 0x21, 0x05, 0x13, 0x11, 0x2A, 0x31, 0x18 ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x11 ]
      - [ 0xB0, 0x6D ]
      - [ 0xB1, 0x37 ]
      - [ 0xB2, 0x81 ]
      - [ 0xB3, 0x80 ]
      - [ 0xB5, 0x43 ]
      - [ 0xB7, 0x85 ]
      - [ 0xB8, 0x20 ]
      - [ 0xC1, 0x78 ]
      - [ 0xC2, 0x78 ]
      - [ 0xD0, 0x88 ]
      - [ 0xE0, 0x00, 0x00, 0x02 ]
      - [ 0xE1, 0x03, 0xA0, 0x00, 0x00, 0x04, 0xA0, 0x00, 0x00, 0x00, 0x20, 0x20 ]
      - [ 0xE2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 ]
      - [ 0xE3, 0x00, 0x00, 0x11, 0x00 ]
      - [ 0xE4, 0x22, 0x00 ]
      - [ 0xE5, 0x05, 0xEC, 0xA0, 0xA0, 0x07, 0xEE, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 ]
      - [ 0xE6, 0x00, 0x00, 0x11, 0x00 ]
      - [ 0xE7, 0x22, 0x00 ]
      - [ 0xE8, 0x06, 0xED, 0xA0, 0xA0, 0x08, 0xEF, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 ]
      - [ 0xEB, 0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x00 ]
      - [ 0xED, 0xFF, 0xFF, 0xFF, 0xBA, 0x0A, 0xBF, 0x45, 0xFF, 0xFF, 0x54, 0xFB, 0xA0, 0xAB, 0xFF, 0xFF, 0xFF ]
      - [ 0xEF, 0x10, 0x0D, 0x04, 0x08, 0x3F, 0x1F ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x13 ]
      - [ 0xEF, 0x08 ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x00 ]
      - [ 0x36, 0x00 ]
      - [ 0x3A, 0x66 ]
      - [ 0x11 ]
      - delay 120ms
      - [ 0x29 ]
      - delay 20ms
    data_pins:
      red:
        - 46       #r1
        - 3        #r2
        - 8        #r3
        - 18       #r4
        - 17       #r5
      green:
        - 14       #g0
        - 13       #g1
        - 12       #g2
        - 11       #g3
        - 10       #g4
        - 9        #g5
      blue:
        - 5        #b1
        - 45       #b2
        - 48       #b3
        - 47       #b4
        - 21       #b5