# https://wiki.seeedstudio.com/xiao-esp32c3-esphome/
esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
