# Complete Example: ESP32 RGB LED Controller
# Hardware: ESP32 + RGB LED strip (common anode or cathode)
# R: GPIO14, G: GPIO12, B: GPIO13

substitutions:
  devicename: rgb_light
  friendly_name: RGB Light
  board_type: esp32dev

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp32:
  board: ${board_type}
  framework:
    type: arduino

<<: !include ../templates/base/wifi.yaml
<<: !include ../templates/base/common.yaml

# RGB LED PWM outputs
output:
  - platform: ledc
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_r
  - platform: ledc
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_g
  - platform: ledc
    pin: GPIO13
    frequency: 1000 Hz
    id: pwm_b

# RGB Light
light:
  - platform: rgb
    name: "${friendly_name}"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    effects:
      - random:
      - strobe:
      - flicker:
