# Complete Example: ESP32 Smart Relay with Button
# Hardware: ESP32 + Relay module + Physical button
# Relay connected to GPIO12, Button connected to GPIO0

substitutions:
  devicename: smart_switch
  friendly_name: Smart Switch
  board_type: esp32dev

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp32:
  board: ${board_type}
  framework:
    type: arduino

<<: !include ../templates/base/wifi.yaml
<<: !include ../templates/base/common.yaml

# Physical button sensor
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay_1

# Relay switch
switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO12
    id: relay_1
    restore_mode: RESTORE_DEFAULT_OFF
