# Complete Example: ESP8266 Temperature & Humidity Sensor
# Hardware: ESP8266 (NodeMCU v2) + DHT22 sensor
# DHT22 data pin connected to GPIO23

substitutions:
  devicename: bedroom_sensor
  friendly_name: Bedroom Sensor
  board_type: nodemcuv2

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp8266:
  board: ${board_type}

<<: !include ../templates/base/wifi.yaml
<<: !include ../templates/base/common.yaml

# DHT22 Temperature and Humidity Sensor
sensor:
  - platform: dht
    pin: GPIO23
    model: DHT22
    temperature:
      name: "${friendly_name} Temperature"
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} Humidity"
      accuracy_decimals: 1
    update_interval: 60s
