# Complete Example: ESP8266 Multi-Sensor Station
# Hardware: ESP8266 + BME280 (I2C) + BH1750 (I2C)
# I2C connections: SDA=GPIO4, SCL=GPIO5

substitutions:
  devicename: weather_station
  friendly_name: Weather Station
  board_type: nodemcuv2

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp8266:
  board: ${board_type}

<<: !include ../templates/base/wifi.yaml
<<: !include ../templates/base/common.yaml

# I2C bus configuration
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

# BME280 Temperature, Humidity and Pressure Sensor
sensor:
  - platform: bme280
    temperature:
      name: "${friendly_name} Temperature"
      oversampling: 16x
      accuracy_decimals: 1
    pressure:
      name: "${friendly_name} Pressure"
      oversampling: 16x
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} Humidity"
      oversampling: 16x
      accuracy_decimals: 1
    address: 0x76
    update_interval: 60s

  # BH1750 Light Sensor
  - platform: bh1750
    name: "${friendly_name} Illuminance"
    address: 0x23
    update_interval: 30s
    accuracy_decimals: 1
