# ESP32 Basic Template
# Common boards: esp32dev, nodemcu-32s, lolin_d32

substitutions:
  devicename: esp32_device
  friendly_name: ESP32 Device
  board_type: esp32dev

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp32:
  board: ${board_type}
  framework:
    type: arduino

<<: !include ../base/wifi.yaml
<<: !include ../base/common.yaml
