# ESP8266 Basic Template
# Common boards: nodemcuv2, d1_mini, d1_mini_pro

substitutions:
  devicename: esp8266_device
  friendly_name: ESP8266 Device
  board_type: nodemcuv2

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp8266:
  board: ${board_type}
  # Optional: Set restore_from_flash for faster boot
  # restore_from_flash: true

<<: !include ../base/wifi.yaml
<<: !include ../base/common.yaml
