# Reusable display sleep package for LVGL-based displays.
# Combines configurable timeout, LVGL pause/resume, keep-awake toggle,
# wake-touch guard, and a remote wake button.
#
# Required substitutions:
#   backlight_id: light id for the display backlight (default: display_backlight_id)
#   touchscreen_id: touchscreen component id for touch input (default: my_touchscreen)
#
# Optional substitutions:
#   default_timeout_seconds: default sleep timeout in seconds (default: 60)
#
# Provides these IDs for consumers to reference:
#   screen_bump_activity (script): call from encoder/other handlers to reset the timeout
#   enter_screen_off (script): force display to sleep immediately
#   exit_screen_off (script): force display to wake immediately
#   screen_is_off (global bool): true when display is sleeping
#   wake_touch (global bool): true on the first touch after waking, consume to ignore wake input
#   keep_display_awake (global bool): true when keep-awake switch is on
#   display_timeout (number): configurable timeout in seconds (10-720)
#   display_keep_awake_switch (switch): toggle to keep display always on
#   wake_display_button (button): press to wake display remotely
#
# Usage:
#   packages:
#     display_sleep:
#       url: https://github.com/rluengen/esphome
#       ref: main
#       files:
#         - path: packages/display/sleep.yaml
#           vars:
#             backlight_id: display_backlight_id
#             touchscreen_id: my_touchscreen

substitutions:
  backlight_id: display_backlight_id
  touchscreen_id: my_touchscreen
  default_timeout_seconds: "60"

number:
  - platform: template
    name: Screen Timeout
    optimistic: true
    entity_category: config
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: ${default_timeout_seconds}
    restore_value: true
    min_value: 10
    max_value: 720
    step: 5
    mode: box

globals:
  - id: screen_is_off
    type: bool
    initial_value: "false"

  - id: wake_touch
    type: bool
    initial_value: "false"

  - id: keep_display_awake
    type: bool
    restore_value: yes
    initial_value: "false"

script:
  # Call whenever user interacts (touch / button / remote wake).
  # Uses mode: restart so each call resets the sleep countdown.
  - id: screen_bump_activity
    mode: restart
    then:
      - if:
          condition:
            lambda: 'return id(screen_is_off);'
          then:
            - script.execute: exit_screen_off
      - if:
          condition:
            lambda: 'return !id(keep_display_awake);'
          then:
            - delay: !lambda 'return (uint32_t)(id(display_timeout).state * 1000);'
            - script.execute: enter_screen_off

  # Put display to sleep: backlight off + LVGL paused
  - id: enter_screen_off
    then:
      - if:
          condition:
            lambda: 'return !id(screen_is_off);'
          then:
            - logger.log: "Putting display to sleep"
            - lambda: 'id(screen_is_off) = true;'
            - light.turn_off: ${backlight_id}
            - lvgl.pause:

  # Wake display: backlight on + LVGL resumed
  - id: exit_screen_off
    then:
      - logger.log: "Waking display"
      - lambda: |-
          id(screen_is_off) = false;
          id(wake_touch) = true;
      - light.turn_on: ${backlight_id}
      - delay: 60ms   # give panel rails time to rise
      - lvgl.resume:

touchscreen:
  - id: !extend ${touchscreen_id}
    on_touch:
      - script.execute: screen_bump_activity

switch:
  - platform: template
    name: "Display Keep Awake"
    id: display_keep_awake_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: 'id(keep_display_awake) = true;'
      - script.execute: exit_screen_off
    turn_off_action:
      - lambda: 'id(keep_display_awake) = false;'
      - script.execute: screen_bump_activity

button:
  - platform: template
    name: "Wake Display"
    id: wake_display_button
    on_press:
      - script.execute: screen_bump_activity
