substitutions:
  sleep_idle_time_milliseconds: 30000
  display_panel_power_switch_id: panel_power

globals:
  - id: last_activity_ms
    type: uint32_t
    restore_value: no
    initial_value: "0"

  - id: screen_is_off
    type: bool
    restore_value: no

  - id: keep_display_awake
    type: bool
    restore_value: yes
    initial_value: "false"

interval:
  - interval: 1s
    then:
      - lambda: |-
          const uint32_t now = millis();
          // Initialize at boot
          if (id(last_activity_ms) == 0) id(last_activity_ms) = now;

          const uint32_t idle_ms = now - id(last_activity_ms);
          // Don't turn off if user explicitly wants to keep the display awake
          if (!id(screen_is_off) && !id(keep_display_awake) && idle_ms > (uint32_t) atoi("${sleep_idle_time_milliseconds}")) {
            id(enter_screen_off).execute();
          }

script:
  # Call whenever user interacts (touch / button / remote wake)
  - id: screen_bump_activity
    then:
      - lambda: |-
          id(last_activity_ms) = millis();
      - if:
          condition:
            lambda: 'return id(screen_is_off);'
          then:
            - script.execute: exit_screen_off

  # Turn off: pick A or B or both
  - id: enter_screen_off
    then:
      - light.turn_off: ${display_panel_power_switch_id}
      - lambda: |-
          id(screen_is_off) = true;

  # Turn on again (first tap wakes; second tap interacts)
  - id: exit_screen_off
    then:
      - light.turn_on: ${display_panel_power_switch_id}
      - delay: 60ms   # give panel rails time to rise
      # Force a redraw so the first frame is crisp
      - lambda: |-
          id(screen_is_off) = false;
          id(last_activity_ms) = millis();   // restart the idle timer

switch:
  - platform: template
    name: "Display Keep Awake"
    id: display_keep_awake_switch
    optimistic: true
    # Replaced `restore_state: yes` (deprecated) with `restore_mode`.
    # Use one of: RESTORE_DEFAULT_OFF, RESTORE_DEFAULT_ON, ALWAYS_OFF, ALWAYS_ON
    # RESTORE_DEFAULT_OFF: restore previous state if present, otherwise default to OFF
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: |-
          id(keep_display_awake) = true;
    turn_off_action:
      - lambda: |-
          id(keep_display_awake) = false;

button:
  - platform: template
    name: "Wake Display"
    id: wake_display_button
    on_press:
      - script.execute: screen_bump_activity
