# Common Device Configuration
substitutions:
  log_level: INFO
  api_encryption_key:
  ota_password:

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:
  encryption:
    key: ${api_encryption_key}
  reboot_timeout: 0s  # Allow device to work without Home Assistant connected
  on_client_connected:
    - logger.log: "Client connected to API"
    - lambda: |-
        ESP_LOGI("api", "HA client connected");
        id(ha_connected).publish_state(true);

  on_client_disconnected:
    - logger.log: "API client disconnected!"
    - lambda: |-
        ESP_LOGW("api", "HA client disconnected");
        id(ha_connected).publish_state(false);

# Enable Over-The-Air updates
ota:
  platform: esphome
  password: ${ota_password}

# Binary sensors for device status
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  - platform: template
    id: ha_connected
    name: "Home Assistant Connected"
    internal: true

# Restart switch
switch:
  - platform: restart
    id: switch_restart
    name: "${friendly_name} Restart"

# Uptime sensor
sensor:
  - platform: uptime
    id: uptime_id
    name: "${friendly_name} Uptime"
    update_interval: 60s

# Text sensor for device information
text_sensor:
  - platform: version
    id: ${device_name}_version
    name: "${friendly_name} ESPHome Version"
    hide_timestamp: true
