# Common Device Configuration
substitutions:
  log_level: INFO
  api_encryption_key:
  ota_password:

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:
  encryption:
    key: ${api_encryption_key}
  reboot_timeout: 0s  # Allow device to work without Home Assistant connected
  on_client_connected:
    - logger.log:
        format: "Client %s connected to API with IP %s"
        args: ["client_info.c_str()", "client_address.c_str()"]
    - lambda: |-
        ESP_LOGI("api", "HA client connected");
        id(ha_connected).publish_state(true);

  on_client_disconnected:
    - logger.log: "API client disconnected!"
    - lambda: |-
        ESP_LOGW("api", "HA client disconnected");
        id(ha_connected).publish_state(false);

# Enable Over-The-Air updates
ota:
  platform: esphome
  password: ${ota_password}

# Binary sensors for device status
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  - platform: template
    id: ha_connected
    name: "Home Assistant Connected"
    internal: true

# Restart switch
switch:
  - platform: restart
    id: switch_restart
    name: "${friendly_name} Restart"

# Uptime sensor
sensor:
  - platform: uptime
    id: uptime_id
    name: "${friendly_name} Uptime"
    update_interval: 60s

  - platform: wifi_signal
    id: wifi_rssi
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    filters:
      - throttle: 5min
    on_value:
      then:
        - lambda: |-
            static int last_bars = -1;
            int bars = 0;
            if (!isnan(id(wifi_rssi).state)) {
              float r = id(wifi_rssi).state;
              if      (r > -55) bars = 4;
              else if (r > -65) bars = 3;
              else if (r > -72) bars = 2;
              else if (r > -80) bars = 1;
              else               bars = 0;
            }

            if (bars != last_bars) {
              last_bars = bars;
              // TODO: the wifi bar count has changed: id(redraw_debounced).execute();
            }

# Text sensor for device information
text_sensor:
  - platform: version
    id: ${device_name}_version
    name: "${friendly_name} ESPHome Version"
    hide_timestamp: true
