# Reusable display timeout package for LVGL-based displays.
# Provides configurable screen timeout with event-driven sleep/wake behavior.
#
# Required substitutions:
#   backlight_id: light id for the display backlight (default: display_backlight_id)
#   touchscreen_id: touchscreen component id for touch input (default: my_touchscreen)
#
# Provides these IDs for consumers to reference:
#   screen_timeout_timer (script): call from encoder/other handlers to reset the timeout
#   screen_is_off (global bool): true when display is sleeping
#   wake_touch (global bool): true on the first touch after waking, consume to ignore wake input
#   display_timeout (number): configurable timeout in seconds (10-720, default 60)
#
# Usage:
#   packages:
#     display_timeout:
#       url: https://github.com/rluengen/esphome
#       ref: main
#       files:
#         - path: packages/display_timeout.yaml
#           vars:
#             backlight_id: display_backlight_id
#             touchscreen_id: my_touchscreen

substitutions:
  backlight_id: display_backlight_id
  touchscreen_id: my_touchscreen

number:
  - platform: template
    name: Screen Timeout
    optimistic: true
    entity_category: config
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 60
    restore_value: true
    min_value: 10
    max_value: 720
    step: 5
    mode: box

globals:
  - id: screen_is_off
    type: bool
    initial_value: "false"

  - id: wake_touch
    type: bool
    initial_value: "false"

script:
  - id: screen_timeout_timer
    mode: restart
    then:
      - delay: !lambda 'return id(display_timeout).state * 1000;'
      - script.execute: put_display_to_sleep

  - id: put_display_to_sleep
    then:
      - if:
          condition:
            lambda: 'return !id(screen_is_off);'
          then:
            - logger.log: "Putting display to sleep"
            - lambda: 'id(screen_is_off) = true;'
            - light.turn_off: ${backlight_id}
            - lvgl.pause:

touchscreen:
  - id: !extend ${touchscreen_id}
    on_touch:
      - script.execute: screen_timeout_timer

lvgl:
  on_resume:
    then:
      - if:
          condition:
            lambda: 'return id(screen_is_off);'
          then:
            - logger.log: "LVGL resumed - restoring backlight"
            - lambda: |-
                id(screen_is_off) = false;
                id(wake_touch) = true;
            - light.turn_on: ${backlight_id}
      - script.execute: screen_timeout_timer
