# For the GPS component to work a UART bus needs to be set in the configuration. Only the RX pin should be necessary.
substitutions:
  tx_pin: 
  rx_pin: 

uart:
  id: gps_uart
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 115200

gps:
  latitude:
    name: "Latitude"
    filters:
      - delta: 0.00001 # ~1 meter
  longitude:
    name: "Longitude"
    filters:
      - delta: 0.00001 # ~1 meter
  altitude:
    name: "Altitude"
    filters:
      - delta: 1.0 # one meter
  satellites:
    name: "Satellites"
    id: gps_satellites
    filters:
      - delta: 1
  hdop:
    name: "Horizontal Dilution of Precision"
    filters:
      - delta: 0.1
  update_interval: 1s

time:
  - platform: gps
    id: gps_time
    on_time_sync:
      then:
        - logger.log: "GPS time synchronized"

select:
  - platform: template
    name: "GPS Update Rate"
    id: gps_rate_select
    optimistic: true
    entity_category: config
    options:
      - "1Hz (Low Power)"
      - "5Hz (Normal)"
      - "10Hz (High Speed)"
    initial_option: "1Hz (Low Power)"
    restore_value: true  # Persist across reboots
    set_action:
      - lambda: |-
          if (x == "1Hz (Low Power)") {
            id(gps_uart).write_str("$$PCAS04,3*1A\r\n");  // Multi-GNSS
            delay(50);
            id(gps_uart).write_str("$$PCAS02,1000*2E\r\n");
          } else if (x == "5Hz (Normal)") {
            id(gps_uart).write_str("$$PCAS04,1*18\r\n");  // GPS only
            delay(50);
            id(gps_uart).write_str("$$PCAS02,200*18\r\n");
          } else if (x == "10Hz (High Speed)") {
            id(gps_uart).write_str("$$PCAS04,1*18\r\n");  // GPS only
            delay(50);
            id(gps_uart).write_str("$$PCAS02,100*1F\r\n");
          }

text_sensor:
  - platform: template
    name: "GPS Time"
    id: gps_time_text
    update_interval: 1s
    lambda: |-
      char buffer[20];
      auto time = id(gps_time).now();
      if (time.is_valid()) {
        snprintf(buffer, sizeof(buffer), "%04d-%02d-%02d %02d:%02d:%02d",
                 time.year, time.month, time.day_of_month,
                 time.hour, time.minute, time.second);
        return {buffer};
      }
      return {"GPS time not available"};

logger:
  baud_rate: 0  # disables UART0 logging, allows GPS UART to be clean