# For the GPS component to work a UART bus needs to be set in the configuration. Only the RX pin should be necessary.
substitutions:
  tx_pin: 
  rx_pin: 

uart:
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 9600

gps:
  latitude:
    name: "Latitude"
  longitude:
    name: "Longitude"
  altitude:
    name: "Altitude"
  satellites:
    name: "Satellites"
  hdop:
    name: "Horizontal Dilution of Precision"
  update_interval: 30s

time:
  - platform: gps
    id: gps_time
    on_time_sync:
      then:
        - logger.log: "GPS time synchronized"

text_sensor:
  - platform: template
    name: "GPS Time"
    id: gps_time_text
    update_interval: 1s
    lambda: |-
      char buffer[20];
      auto time = id(gps_time).now();
      if (time.is_valid()) {
        snprintf(buffer, sizeof(buffer), "%04d-%02d-%02d %02d:%02d:%02d",
                 time.year, time.month, time.day_of_month,
                 time.hour, time.minute, time.second);
        return {buffer};
      }
      return {"GPS time not available"};

logger:
  baud_rate: 0  # disables UART0 logging, allows GPS UART to be clean