substitutions:
  wizmote_mac_address:

external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote

esp_now:

wizmote:
#  mac_address: ${wizmote_mac_address}
  on_button:
    - logger.log: "Wizmote button pushed! data.button "

wifi:
  power_save_mode: none
