substitutions:
  wizmote_mac_address:

external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote

esp_now:

wizmote:
#  mac_address: ${wizmote_mac_address}
  on_button:
    - lambda: |-
        ESP_LOGI("button", "Button pressed! Pin=%d", data.button);
        if (data.button == 1) {
          id(wizmote_on).publish_state(true);
        } else if (data.button == 2) {
          id(wizmote_off).publish_state(true);
        } else if (data.button == 3) {
          id(wizmote_sleep).publish_state(true);
        } else if (data.button == 16) {
          id(wizmote_1).publish_state(true);
        } else if (data.button == 17) {
          id(wizmote_2).publish_state(true);
        } else if (data.button == 18) {
          id(wizmote_3).publish_state(true);
        } else if (data.button == 19) {
          id(wizmote_4).publish_state(true);
        } else if (data.button == 8) {
          id(wizmote_down).publish_state(true);
        } else if (data.button == 9) {
          id(wizmote_up).publish_state(true);
        }

        // Reset them back to false so they act like momentary presses
        id(wizmote_on).publish_state(false);
        id(wizmote_off).publish_state(false);

        id(wizmote_sleep).publish_state(false);

        id(wizmote_1).publish_state(false);
        id(wizmote_2).publish_state(false);
        id(wizmote_3).publish_state(false);
        id(wizmote_4).publish_state(false);

        id(wizmote_up).publish_state(false);
        id(wizmote_down).publish_state(false);

wifi:
  power_save_mode: none
  fast_connect: true

binary_sensor:
    # Wizmote Pin 1
  - platform: template
    id: wizmote_on
    name: "Wizmote On"
    lambda: 'return false;'

    # Wizmote Pin 2
  - platform: template
    id: wizmote_off
    name: "Wizmote Off"
    lambda: 'return false;'

    # Wizmote Pin 3
  - platform: template
    id: wizmote_sleep
    name: "Wizmote Sleep"
    lambda: 'return false;'

    # Wizmote Pin 16
  - platform: template
    id: wizmote_1
    name: "Wizmote 1"
    lambda: 'return false;'

    # Wizmote Pin 17
  - platform: template
    id: wizmote_2
    name: "Wizmote 2"
    lambda: 'return false;'

    # Wizmote Pin 18
  - platform: template
    id: wizmote_3
    name: "Wizmote 3"
    lambda: 'return false;'

    # Wizmote Pin 19
  - platform: template
    id: wizmote_4
    name: "Wizmote 4"
    lambda: 'return false;'

    # Wizmote Pin 8
  - platform: template
    id: wizmote_down
    name: "Wizmote -"
    lambda: 'return false;'

    # Wizmote Pin 9
  - platform: template
    id: wizmote_up
    name: "Wizmote +"
    lambda: 'return false;'
