substitutions:
  wizmote_mac_address:

external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote

esp_now:

wizmote:
#  mac_address: ${wizmote_mac_address}
  on_button:
    - lambda: |-
        ESP_LOGI("button", "Button pressed! Pin=%d", data.button);
wifi:
  power_save_mode: none
