substitutions:
  wizmote_mac_address:

external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote

esp_now:

wizmote:
  mac_address: ${wizmote_mac_address}

binary_sensor:
  - platform: wizmote
    button: 1
    name: "WizMote Button 1"

  - platform: wizmote
    button: 2
    name: "WizMote Button 2"

  - platform: wizmote
    button: 3
    name: "WizMote Button 3"

  - platform: wizmote
    button: 4
    name: "WizMote Button 4"
