# https://pictogrammers.com/library/mdi/

substitutions:
  icon_bpp: 4

font:
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: battery_icons
    size: 20
    bpp: ${icon_bpp}
    glyphs: [
      "\U000F007A", # mdi-battery-10
      "\U000F007B", # mdi-battery-20
      "\U000F007C", # mdi-battery-30
      "\U000F007D", # mdi-battery-40
      "\U000F007E", # mdi-battery-50
      "\U000F007F", # mdi-battery-60
      "\U000F0080", # mdi-battery-70
      "\U000F0081", # mdi-battery-80
      "\U000F0082", # mdi-battery-90
      "\U000F0079", # mdi-battery (full)
      "\U000F008E", # mdi-battery-outline
      "\U000F0091", # mdi-battery-unknown

      "\U000F0086", # battery-charging-20
      "\U000F0087", # battery-charging-30
      "\U000F0088", # battery-charging-40
      "\U000F0089", # battery-charging-60
      "\U000F008A", # battery-charging-80
      "\U000F008B", # battery-charging-90

      "\U000F1C3B", # power-plug-battery
      "\U000F1C3C", # power-plug-battery-outline

      ]
