# https://pictogrammers.com/library/mdi/

substitutions:
  icon_bpp: 4

font:
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: homeassistant_icons
    size: 20
    bpp: ${icon_bpp}
    glyphs: [
      "\U000F07D0", # mdi-home-assistant
      "\U000F06A1", # mdi-home-outline (connected)
      "\U000F0F21", # mdi-home-off (disconnected)
      "\U000F0028", # alert-circle
      ]

# F13D7 home-remove-outline https://pictogrammers.com/library/mdi/icon/home-remove-outline/
# F06A1 home-outline